/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_preferences (void)
{
  GtkWidget *window_preferences;
  GtkWidget *preferences_vbox;
  GtkWidget *preferences_notebook;
  GtkWidget *preferences_working_dir_vbox;
  GtkWidget *preferences_working_dir_vbox_vbox;
  GtkWidget *preferences_working_dir_label;
  GtkWidget *hbox3;
  GtkWidget *label72;
  GtkWidget *vbox12;
  GtkWidget *preferences_working_dir_entry;
  GtkWidget *label50;
  GtkWidget *preferences_sources_vbox;
  GtkWidget *vbox38;
  GtkWidget *preferences_sources_label;
  GtkWidget *hbox75;
  GtkWidget *preferences_sources_empty_label;
  GtkWidget *preferences_sources_hbox;
  GtkWidget *scrolledwindow1;
  GtkWidget *preferences_sources_treeview;
  GtkWidget *vbox39;
  GtkWidget *preferences_add_source_button;
  GtkWidget *preferences_remove_source_button;
  GtkWidget *label118;
  GtkWidget *preferences_exclude_vbox;
  GtkWidget *preferences_exclude_vbox_vbox;
  GtkWidget *preferences_exclude_label;
  GtkWidget *hbox81;
  GtkWidget *label140;
  GtkWidget *hbox82;
  GtkWidget *scrolledwindow12;
  GtkWidget *preferences_exclude_treeview;
  GtkWidget *vbox42;
  GtkWidget *preferences_add_exclude_button;
  GtkWidget *preferences_remove_exclude_button;
  GtkWidget *label51;
  GtkWidget *preferences_hbuttonbox;
  GtkWidget *preferences_apply_button;
  GtkWidget *preferences_close_button;
  GtkWidget *preferences_ok_button;

  window_preferences = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window_preferences, "window_preferences");
  gtk_window_set_title (GTK_WINDOW (window_preferences), _("Preferences"));
  gtk_window_set_position (GTK_WINDOW (window_preferences), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (window_preferences), TRUE);

  preferences_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (preferences_vbox, "preferences_vbox");
  gtk_widget_show (preferences_vbox);
  gtk_container_add (GTK_CONTAINER (window_preferences), preferences_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_vbox), 6);

  preferences_notebook = gtk_notebook_new ();
  gtk_widget_set_name (preferences_notebook, "preferences_notebook");
  gtk_widget_show (preferences_notebook);
  gtk_box_pack_start (GTK_BOX (preferences_vbox), preferences_notebook, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_notebook), 6);

  preferences_working_dir_vbox = gtk_vbox_new (FALSE, 18);
  gtk_widget_set_name (preferences_working_dir_vbox, "preferences_working_dir_vbox");
  gtk_widget_show (preferences_working_dir_vbox);
  gtk_container_add (GTK_CONTAINER (preferences_notebook), preferences_working_dir_vbox);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (preferences_notebook), preferences_working_dir_vbox,
                                      FALSE, FALSE, GTK_PACK_START);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_working_dir_vbox), 12);

  preferences_working_dir_vbox_vbox = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (preferences_working_dir_vbox_vbox, "preferences_working_dir_vbox_vbox");
  gtk_widget_show (preferences_working_dir_vbox_vbox);
  gtk_box_pack_start (GTK_BOX (preferences_working_dir_vbox), preferences_working_dir_vbox_vbox, FALSE, FALSE, 0);

  preferences_working_dir_label = gtk_label_new (_("<b>Package and data storage</b>"));
  gtk_widget_set_name (preferences_working_dir_label, "preferences_working_dir_label");
  gtk_widget_show (preferences_working_dir_label);
  gtk_box_pack_start (GTK_BOX (preferences_working_dir_vbox_vbox), preferences_working_dir_label, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (preferences_working_dir_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (preferences_working_dir_label), 0, 0.5);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (preferences_working_dir_vbox_vbox), hbox3, FALSE, FALSE, 0);

  label72 = gtk_label_new (_("    "));
  gtk_widget_set_name (label72, "label72");
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox3), label72, FALSE, FALSE, 0);

  vbox12 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox12, "vbox12");
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox12, FALSE, FALSE, 0);

  preferences_working_dir_entry = gtk_entry_new ();
  gtk_widget_set_name (preferences_working_dir_entry, "preferences_working_dir_entry");
  gtk_widget_show (preferences_working_dir_entry);
  gtk_box_pack_start (GTK_BOX (vbox12), preferences_working_dir_entry, FALSE, FALSE, 0);

  label50 = gtk_label_new (_("Working Directory"));
  gtk_widget_set_name (label50, "label50");
  gtk_widget_show (label50);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (preferences_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (preferences_notebook), 0), label50);
  gtk_label_set_justify (GTK_LABEL (label50), GTK_JUSTIFY_CENTER);

  preferences_sources_vbox = gtk_vbox_new (FALSE, 18);
  gtk_widget_set_name (preferences_sources_vbox, "preferences_sources_vbox");
  gtk_widget_show (preferences_sources_vbox);
  gtk_container_add (GTK_CONTAINER (preferences_notebook), preferences_sources_vbox);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (preferences_notebook), preferences_sources_vbox,
                                      FALSE, FALSE, GTK_PACK_START);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_sources_vbox), 12);

  vbox38 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox38, "vbox38");
  gtk_widget_show (vbox38);
  gtk_box_pack_start (GTK_BOX (preferences_sources_vbox), vbox38, FALSE, FALSE, 0);

  preferences_sources_label = gtk_label_new (_("<b>Package Sources</b>"));
  gtk_widget_set_name (preferences_sources_label, "preferences_sources_label");
  gtk_widget_show (preferences_sources_label);
  gtk_box_pack_start (GTK_BOX (vbox38), preferences_sources_label, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (preferences_sources_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (preferences_sources_label), 0, 0.5);

  hbox75 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox75, "hbox75");
  gtk_widget_show (hbox75);
  gtk_box_pack_start (GTK_BOX (vbox38), hbox75, TRUE, TRUE, 0);
  gtk_widget_set_size_request (hbox75, -1, 174);

  preferences_sources_empty_label = gtk_label_new (_("    "));
  gtk_widget_set_name (preferences_sources_empty_label, "preferences_sources_empty_label");
  gtk_widget_show (preferences_sources_empty_label);
  gtk_box_pack_start (GTK_BOX (hbox75), preferences_sources_empty_label, FALSE, FALSE, 0);

  preferences_sources_hbox = gtk_hbox_new (FALSE, 12);
  gtk_widget_set_name (preferences_sources_hbox, "preferences_sources_hbox");
  gtk_widget_show (preferences_sources_hbox);
  gtk_box_pack_start (GTK_BOX (hbox75), preferences_sources_hbox, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (preferences_sources_hbox), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  preferences_sources_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (preferences_sources_treeview, "preferences_sources_treeview");
  gtk_widget_show (preferences_sources_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), preferences_sources_treeview);

  vbox39 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox39, "vbox39");
  gtk_widget_show (vbox39);
  gtk_box_pack_start (GTK_BOX (preferences_sources_hbox), vbox39, FALSE, FALSE, 0);

  preferences_add_source_button = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_set_name (preferences_add_source_button, "preferences_add_source_button");
  gtk_widget_show (preferences_add_source_button);
  gtk_box_pack_start (GTK_BOX (vbox39), preferences_add_source_button, FALSE, FALSE, 0);

  preferences_remove_source_button = gtk_button_new_from_stock ("gtk-remove");
  gtk_widget_set_name (preferences_remove_source_button, "preferences_remove_source_button");
  gtk_widget_show (preferences_remove_source_button);
  gtk_box_pack_start (GTK_BOX (vbox39), preferences_remove_source_button, FALSE, FALSE, 0);

  label118 = gtk_label_new (_("Sources"));
  gtk_widget_set_name (label118, "label118");
  gtk_widget_show (label118);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (preferences_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (preferences_notebook), 1), label118);

  preferences_exclude_vbox = gtk_vbox_new (FALSE, 18);
  gtk_widget_set_name (preferences_exclude_vbox, "preferences_exclude_vbox");
  gtk_widget_show (preferences_exclude_vbox);
  gtk_container_add (GTK_CONTAINER (preferences_notebook), preferences_exclude_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_exclude_vbox), 12);

  preferences_exclude_vbox_vbox = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (preferences_exclude_vbox_vbox, "preferences_exclude_vbox_vbox");
  gtk_widget_show (preferences_exclude_vbox_vbox);
  gtk_box_pack_start (GTK_BOX (preferences_exclude_vbox), preferences_exclude_vbox_vbox, FALSE, FALSE, 0);

  preferences_exclude_label = gtk_label_new (_("<b>Exclude List</b>"));
  gtk_widget_set_name (preferences_exclude_label, "preferences_exclude_label");
  gtk_widget_show (preferences_exclude_label);
  gtk_box_pack_start (GTK_BOX (preferences_exclude_vbox_vbox), preferences_exclude_label, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (preferences_exclude_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (preferences_exclude_label), 0, 0.5);

  hbox81 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox81, "hbox81");
  gtk_widget_show (hbox81);
  gtk_box_pack_start (GTK_BOX (preferences_exclude_vbox_vbox), hbox81, TRUE, TRUE, 0);
  gtk_widget_set_size_request (hbox81, -1, 174);

  label140 = gtk_label_new (_("    "));
  gtk_widget_set_name (label140, "label140");
  gtk_widget_show (label140);
  gtk_box_pack_start (GTK_BOX (hbox81), label140, FALSE, FALSE, 0);

  hbox82 = gtk_hbox_new (FALSE, 12);
  gtk_widget_set_name (hbox82, "hbox82");
  gtk_widget_show (hbox82);
  gtk_box_pack_start (GTK_BOX (hbox81), hbox82, TRUE, TRUE, 0);

  scrolledwindow12 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow12, "scrolledwindow12");
  gtk_widget_show (scrolledwindow12);
  gtk_box_pack_start (GTK_BOX (hbox82), scrolledwindow12, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow12), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow12), GTK_SHADOW_IN);

  preferences_exclude_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (preferences_exclude_treeview, "preferences_exclude_treeview");
  gtk_widget_show (preferences_exclude_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow12), preferences_exclude_treeview);

  vbox42 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox42, "vbox42");
  gtk_widget_show (vbox42);
  gtk_box_pack_start (GTK_BOX (hbox82), vbox42, FALSE, FALSE, 0);

  preferences_add_exclude_button = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_set_name (preferences_add_exclude_button, "preferences_add_exclude_button");
  gtk_widget_show (preferences_add_exclude_button);
  gtk_box_pack_start (GTK_BOX (vbox42), preferences_add_exclude_button, FALSE, FALSE, 0);

  preferences_remove_exclude_button = gtk_button_new_from_stock ("gtk-remove");
  gtk_widget_set_name (preferences_remove_exclude_button, "preferences_remove_exclude_button");
  gtk_widget_show (preferences_remove_exclude_button);
  gtk_box_pack_start (GTK_BOX (vbox42), preferences_remove_exclude_button, FALSE, FALSE, 0);

  label51 = gtk_label_new (_("Excludes"));
  gtk_widget_set_name (label51, "label51");
  gtk_widget_show (label51);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (preferences_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (preferences_notebook), 2), label51);
  gtk_label_set_justify (GTK_LABEL (label51), GTK_JUSTIFY_CENTER);

  preferences_hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_set_name (preferences_hbuttonbox, "preferences_hbuttonbox");
  gtk_widget_show (preferences_hbuttonbox);
  gtk_box_pack_start (GTK_BOX (preferences_vbox), preferences_hbuttonbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_hbuttonbox), 6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (preferences_hbuttonbox), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (preferences_hbuttonbox), 6);

  preferences_apply_button = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (preferences_apply_button, "preferences_apply_button");
  gtk_widget_show (preferences_apply_button);
  gtk_container_add (GTK_CONTAINER (preferences_hbuttonbox), preferences_apply_button);
  GTK_WIDGET_SET_FLAGS (preferences_apply_button, GTK_CAN_DEFAULT);

  preferences_close_button = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (preferences_close_button, "preferences_close_button");
  gtk_widget_show (preferences_close_button);
  gtk_container_add (GTK_CONTAINER (preferences_hbuttonbox), preferences_close_button);
  GTK_WIDGET_SET_FLAGS (preferences_close_button, GTK_CAN_DEFAULT);

  preferences_ok_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (preferences_ok_button, "preferences_ok_button");
  gtk_widget_show (preferences_ok_button);
  gtk_container_add (GTK_CONTAINER (preferences_hbuttonbox), preferences_ok_button);
  GTK_WIDGET_SET_FLAGS (preferences_ok_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) window_preferences, "destroy_event",
                    G_CALLBACK (gtk_widget_destroy),
                    NULL);
  g_signal_connect ((gpointer) preferences_add_source_button, "clicked",
                    G_CALLBACK (preferences_sources_add),
                    NULL);
  g_signal_connect ((gpointer) preferences_remove_source_button, "clicked",
                    G_CALLBACK (preferences_sources_remove),
                    NULL);
  g_signal_connect ((gpointer) preferences_add_exclude_button, "clicked",
                    G_CALLBACK (preferences_exclude_add),
                    NULL);
  g_signal_connect ((gpointer) preferences_remove_exclude_button, "clicked",
                    G_CALLBACK (preferences_exclude_remove),
                    NULL);
  g_signal_connect_swapped ((gpointer) preferences_apply_button, "clicked",
                            G_CALLBACK (preferences_on_apply_clicked),
                            GTK_OBJECT (window_preferences));
  g_signal_connect_swapped ((gpointer) preferences_close_button, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (window_preferences));
  g_signal_connect_swapped ((gpointer) preferences_ok_button, "clicked",
                            G_CALLBACK (preferences_on_ok_clicked),
                            GTK_OBJECT (window_preferences));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_preferences, window_preferences, "window_preferences");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_vbox, "preferences_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_notebook, "preferences_notebook");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_working_dir_vbox, "preferences_working_dir_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_working_dir_vbox_vbox, "preferences_working_dir_vbox_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_working_dir_label, "preferences_working_dir_label");
  GLADE_HOOKUP_OBJECT (window_preferences, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_preferences, label72, "label72");
  GLADE_HOOKUP_OBJECT (window_preferences, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_working_dir_entry, "preferences_working_dir_entry");
  GLADE_HOOKUP_OBJECT (window_preferences, label50, "label50");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_sources_vbox, "preferences_sources_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, vbox38, "vbox38");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_sources_label, "preferences_sources_label");
  GLADE_HOOKUP_OBJECT (window_preferences, hbox75, "hbox75");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_sources_empty_label, "preferences_sources_empty_label");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_sources_hbox, "preferences_sources_hbox");
  GLADE_HOOKUP_OBJECT (window_preferences, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_sources_treeview, "preferences_sources_treeview");
  GLADE_HOOKUP_OBJECT (window_preferences, vbox39, "vbox39");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_add_source_button, "preferences_add_source_button");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_remove_source_button, "preferences_remove_source_button");
  GLADE_HOOKUP_OBJECT (window_preferences, label118, "label118");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_exclude_vbox, "preferences_exclude_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_exclude_vbox_vbox, "preferences_exclude_vbox_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_exclude_label, "preferences_exclude_label");
  GLADE_HOOKUP_OBJECT (window_preferences, hbox81, "hbox81");
  GLADE_HOOKUP_OBJECT (window_preferences, label140, "label140");
  GLADE_HOOKUP_OBJECT (window_preferences, hbox82, "hbox82");
  GLADE_HOOKUP_OBJECT (window_preferences, scrolledwindow12, "scrolledwindow12");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_exclude_treeview, "preferences_exclude_treeview");
  GLADE_HOOKUP_OBJECT (window_preferences, vbox42, "vbox42");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_add_exclude_button, "preferences_add_exclude_button");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_remove_exclude_button, "preferences_remove_exclude_button");
  GLADE_HOOKUP_OBJECT (window_preferences, label51, "label51");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_hbuttonbox, "preferences_hbuttonbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_apply_button, "preferences_apply_button");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_close_button, "preferences_close_button");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_ok_button, "preferences_ok_button");

  return window_preferences;
}

GtkWidget*
create_transaction_window (void)
{
  GtkWidget *transaction_window;
  GtkWidget *transaction_vbox;
  GtkWidget *transaction_vbox_vbox;
  GtkWidget *vbox23;
  GtkWidget *transaction_label;
  GtkWidget *transaction_progressbar;
  GtkWidget *transaction_exclude_expander;
  GtkWidget *vbox27;
  GtkWidget *scrolledwindow11;
  GtkWidget *transaction_exclude_treeview;
  GtkWidget *label9;
  GtkWidget *transaction_install_expander;
  GtkWidget *vbox24;
  GtkWidget *transaction_install;
  GtkWidget *transaction_install_treeview;
  GtkWidget *label6;
  GtkWidget *transaction_upgrade_expander;
  GtkWidget *vbox25;
  GtkWidget *scrolledwindow9;
  GtkWidget *transaction_upgrade_treeview;
  GtkWidget *label7;
  GtkWidget *transaction_remove_expander;
  GtkWidget *vbox26;
  GtkWidget *scrolledwindow10;
  GtkWidget *transaction_remove_treeview;
  GtkWidget *label8;
  GtkWidget *transaction_hbuttonbox;
  GtkWidget *transaction_cancelbutton;
  GtkWidget *transaction_okbutton1;

  transaction_window = gtk_dialog_new ();
  gtk_widget_set_name (transaction_window, "transaction_window");
  gtk_window_set_title (GTK_WINDOW (transaction_window), _("Transaction Report"));
  gtk_window_set_type_hint (GTK_WINDOW (transaction_window), GDK_WINDOW_TYPE_HINT_DIALOG);

  transaction_vbox = GTK_DIALOG (transaction_window)->vbox;
  gtk_widget_set_name (transaction_vbox, "transaction_vbox");
  gtk_widget_show (transaction_vbox);

  transaction_vbox_vbox = gtk_vbox_new (FALSE, 12);
  gtk_widget_set_name (transaction_vbox_vbox, "transaction_vbox_vbox");
  gtk_widget_show (transaction_vbox_vbox);
  gtk_box_pack_start (GTK_BOX (transaction_vbox), transaction_vbox_vbox, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (transaction_vbox_vbox), 6);

  vbox23 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox23, "vbox23");
  gtk_widget_show (vbox23);
  gtk_box_pack_start (GTK_BOX (transaction_vbox_vbox), vbox23, FALSE, FALSE, 0);

  transaction_label = gtk_label_new ("");
  gtk_widget_set_name (transaction_label, "transaction_label");
  gtk_widget_show (transaction_label);
  gtk_box_pack_start (GTK_BOX (vbox23), transaction_label, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (transaction_label), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (transaction_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (transaction_label), 0, 0.5);

  transaction_progressbar = gtk_progress_bar_new ();
  gtk_widget_set_name (transaction_progressbar, "transaction_progressbar");
  gtk_widget_show (transaction_progressbar);
  gtk_box_pack_start (GTK_BOX (vbox23), transaction_progressbar, FALSE, FALSE, 0);

  transaction_exclude_expander = gtk_expander_new (NULL);
  gtk_widget_set_name (transaction_exclude_expander, "transaction_exclude_expander");
  gtk_widget_show (transaction_exclude_expander);
  gtk_box_pack_start (GTK_BOX (transaction_vbox_vbox), transaction_exclude_expander, FALSE, FALSE, 0);
  gtk_expander_set_spacing (GTK_EXPANDER (transaction_exclude_expander), 6);

  vbox27 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox27, "vbox27");
  gtk_widget_show (vbox27);
  gtk_container_add (GTK_CONTAINER (transaction_exclude_expander), vbox27);

  scrolledwindow11 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow11, "scrolledwindow11");
  gtk_widget_show (scrolledwindow11);
  gtk_box_pack_start (GTK_BOX (vbox27), scrolledwindow11, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindow11, -1, 200);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow11), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow11), GTK_SHADOW_IN);

  transaction_exclude_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (transaction_exclude_treeview, "transaction_exclude_treeview");
  gtk_widget_show (transaction_exclude_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow11), transaction_exclude_treeview);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (transaction_exclude_treeview), FALSE);

  label9 = gtk_label_new (_("Packages Excluded"));
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_expander_set_label_widget (GTK_EXPANDER (transaction_exclude_expander), label9);

  transaction_install_expander = gtk_expander_new (NULL);
  gtk_widget_set_name (transaction_install_expander, "transaction_install_expander");
  gtk_widget_show (transaction_install_expander);
  gtk_box_pack_start (GTK_BOX (transaction_vbox_vbox), transaction_install_expander, FALSE, FALSE, 0);
  gtk_expander_set_spacing (GTK_EXPANDER (transaction_install_expander), 6);

  vbox24 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox24, "vbox24");
  gtk_widget_show (vbox24);
  gtk_container_add (GTK_CONTAINER (transaction_install_expander), vbox24);

  transaction_install = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (transaction_install, "transaction_install");
  gtk_widget_show (transaction_install);
  gtk_box_pack_start (GTK_BOX (vbox24), transaction_install, TRUE, TRUE, 0);
  gtk_widget_set_size_request (transaction_install, -1, 200);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (transaction_install), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (transaction_install), GTK_SHADOW_IN);

  transaction_install_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (transaction_install_treeview, "transaction_install_treeview");
  gtk_widget_show (transaction_install_treeview);
  gtk_container_add (GTK_CONTAINER (transaction_install), transaction_install_treeview);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (transaction_install_treeview), FALSE);

  label6 = gtk_label_new (_("Packages to Install"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_expander_set_label_widget (GTK_EXPANDER (transaction_install_expander), label6);

  transaction_upgrade_expander = gtk_expander_new (NULL);
  gtk_widget_set_name (transaction_upgrade_expander, "transaction_upgrade_expander");
  gtk_widget_show (transaction_upgrade_expander);
  gtk_box_pack_start (GTK_BOX (transaction_vbox_vbox), transaction_upgrade_expander, FALSE, FALSE, 0);
  gtk_expander_set_spacing (GTK_EXPANDER (transaction_upgrade_expander), 6);

  vbox25 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox25, "vbox25");
  gtk_widget_show (vbox25);
  gtk_container_add (GTK_CONTAINER (transaction_upgrade_expander), vbox25);

  scrolledwindow9 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow9, "scrolledwindow9");
  gtk_widget_show (scrolledwindow9);
  gtk_box_pack_start (GTK_BOX (vbox25), scrolledwindow9, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindow9, -1, 200);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow9), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow9), GTK_SHADOW_IN);

  transaction_upgrade_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (transaction_upgrade_treeview, "transaction_upgrade_treeview");
  gtk_widget_show (transaction_upgrade_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow9), transaction_upgrade_treeview);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (transaction_upgrade_treeview), FALSE);

  label7 = gtk_label_new (_("Packages to Upgrade"));
  gtk_widget_set_name (label7, "label7");
  gtk_widget_show (label7);
  gtk_expander_set_label_widget (GTK_EXPANDER (transaction_upgrade_expander), label7);

  transaction_remove_expander = gtk_expander_new (NULL);
  gtk_widget_set_name (transaction_remove_expander, "transaction_remove_expander");
  gtk_widget_show (transaction_remove_expander);
  gtk_box_pack_start (GTK_BOX (transaction_vbox_vbox), transaction_remove_expander, FALSE, FALSE, 0);
  gtk_expander_set_spacing (GTK_EXPANDER (transaction_remove_expander), 6);

  vbox26 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox26, "vbox26");
  gtk_widget_show (vbox26);
  gtk_container_add (GTK_CONTAINER (transaction_remove_expander), vbox26);

  scrolledwindow10 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow10, "scrolledwindow10");
  gtk_widget_show (scrolledwindow10);
  gtk_box_pack_start (GTK_BOX (vbox26), scrolledwindow10, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindow10, -1, 200);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow10), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow10), GTK_SHADOW_IN);

  transaction_remove_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (transaction_remove_treeview, "transaction_remove_treeview");
  gtk_widget_show (transaction_remove_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow10), transaction_remove_treeview);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (transaction_remove_treeview), FALSE);

  label8 = gtk_label_new (_("Packages to Remove"));
  gtk_widget_set_name (label8, "label8");
  gtk_widget_show (label8);
  gtk_expander_set_label_widget (GTK_EXPANDER (transaction_remove_expander), label8);

  transaction_hbuttonbox = GTK_DIALOG (transaction_window)->action_area;
  gtk_widget_set_name (transaction_hbuttonbox, "transaction_hbuttonbox");
  gtk_widget_show (transaction_hbuttonbox);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (transaction_hbuttonbox), GTK_BUTTONBOX_END);

  transaction_cancelbutton = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (transaction_cancelbutton, "transaction_cancelbutton");
  gtk_widget_show (transaction_cancelbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (transaction_window), transaction_cancelbutton, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (transaction_cancelbutton, GTK_CAN_DEFAULT);

  transaction_okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (transaction_okbutton1, "transaction_okbutton1");
  gtk_widget_show (transaction_okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (transaction_window), transaction_okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (transaction_okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) transaction_window, "close",
                    G_CALLBACK (gtk_widget_destroy),
                    NULL);
  g_signal_connect ((gpointer) transaction_window, "destroy_event",
                    G_CALLBACK (gtk_widget_destroy),
                    NULL);
  g_signal_connect_swapped ((gpointer) transaction_cancelbutton, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (transaction_window));
  g_signal_connect_swapped ((gpointer) transaction_okbutton1, "clicked",
                            G_CALLBACK (on_transaction_okbutton1_clicked),
                            GTK_OBJECT (transaction_window));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (transaction_window, transaction_window, "transaction_window");
  GLADE_HOOKUP_OBJECT_NO_REF (transaction_window, transaction_vbox, "transaction_vbox");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_vbox_vbox, "transaction_vbox_vbox");
  GLADE_HOOKUP_OBJECT (transaction_window, vbox23, "vbox23");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_label, "transaction_label");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_progressbar, "transaction_progressbar");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_exclude_expander, "transaction_exclude_expander");
  GLADE_HOOKUP_OBJECT (transaction_window, vbox27, "vbox27");
  GLADE_HOOKUP_OBJECT (transaction_window, scrolledwindow11, "scrolledwindow11");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_exclude_treeview, "transaction_exclude_treeview");
  GLADE_HOOKUP_OBJECT (transaction_window, label9, "label9");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_install_expander, "transaction_install_expander");
  GLADE_HOOKUP_OBJECT (transaction_window, vbox24, "vbox24");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_install, "transaction_install");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_install_treeview, "transaction_install_treeview");
  GLADE_HOOKUP_OBJECT (transaction_window, label6, "label6");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_upgrade_expander, "transaction_upgrade_expander");
  GLADE_HOOKUP_OBJECT (transaction_window, vbox25, "vbox25");
  GLADE_HOOKUP_OBJECT (transaction_window, scrolledwindow9, "scrolledwindow9");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_upgrade_treeview, "transaction_upgrade_treeview");
  GLADE_HOOKUP_OBJECT (transaction_window, label7, "label7");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_remove_expander, "transaction_remove_expander");
  GLADE_HOOKUP_OBJECT (transaction_window, vbox26, "vbox26");
  GLADE_HOOKUP_OBJECT (transaction_window, scrolledwindow10, "scrolledwindow10");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_remove_treeview, "transaction_remove_treeview");
  GLADE_HOOKUP_OBJECT (transaction_window, label8, "label8");
  GLADE_HOOKUP_OBJECT_NO_REF (transaction_window, transaction_hbuttonbox, "transaction_hbuttonbox");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_cancelbutton, "transaction_cancelbutton");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_okbutton1, "transaction_okbutton1");

  return transaction_window;
}

GtkWidget*
create_gslapt (void)
{
  GtkWidget *gslapt;
  GtkWidget *gslapt_vbox;
  GtkWidget *top_menubar;
  GtkWidget *actions2;
  GtkWidget *actions2_menu;
  GtkWidget *update2;
  GtkWidget *image831;
  GtkWidget *upgrade2;
  GtkWidget *image832;
  GtkWidget *dist_upgrade2;
  GtkWidget *image833;
  GtkWidget *execute2;
  GtkWidget *image834;
  GtkWidget *separator5;
  GtkWidget *quit;
  GtkWidget *settings1;
  GtkWidget *settings1_menu;
  GtkWidget *preferences2;
  GtkWidget *image835;
  GtkWidget *help3;
  GtkWidget *help3_menu;
  GtkWidget *about3;
  GtkWidget *image836;
  GtkWidget *action_toolbar;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *action_bar_update_button;
  GtkWidget *action_bar_upgrade_button;
  GtkWidget *action_bar_dist_upgrade_button;
  GtkWidget *action_bar_execute_button;
  GtkWidget *action_bar_quit_button;
  GtkWidget *pkg_notebook_info_actionbox;
  GtkWidget *pkg_notebook;
  GtkWidget *search_tab_vbox;
  GtkWidget *search_tab_search_align;
  GtkWidget *search_tab_search_hbox;
  GtkWidget *search_tab_search_entry;
  GtkWidget *search_tab_search_button;
  GtkWidget *search_tab_clear_button;
  GtkWidget *search_tab_search_results_scrolled;
  GtkWidget *pkg_listing_treeview;
  GtkWidget *search_tab;
  GtkWidget *pkg_info_action_hbox;
  GtkWidget *pkg_info_frame;
  GtkWidget *pkg_info_action_table;
  GtkWidget *pkg_info_action_name_label;
  GtkWidget *pkg_info_action_conflicts_entry;
  GtkWidget *pkg_info_action_mirror_label;
  GtkWidget *pkg_info_action_location_label;
  GtkWidget *pkg_info_action_version_label;
  GtkWidget *pkg_info_action_size_label;
  GtkWidget *pkg_info_action_isize_label;
  GtkWidget *pkg_info_action_name_entry;
  GtkWidget *pkg_info_action_mirror_entry;
  GtkWidget *pkg_info_action_location_entry;
  GtkWidget *pkg_info_action_version_entry;
  GtkWidget *pkg_info_action_size_entry;
  GtkWidget *pkg_info_action_isize_entry;
  GtkWidget *pkg_info_action_required_entry;
  GtkWidget *pkg_info_action_description_entry;
  GtkWidget *pkg_info_action_suggests_entry;
  GtkWidget *pkg_info_action_description_label;
  GtkWidget *pkg_info_action_conflicts_label;
  GtkWidget *pkg_info_action_suggests_label;
  GtkWidget *pkg_info_action_required_label;
  GtkWidget *pkg_info_label;
  GtkWidget *pkg_action_frame;
  GtkWidget *pkg_action_vbox;
  GtkWidget *pkg_info_action_install_upgrade_button;
  GtkWidget *alignment27;
  GtkWidget *hbox78;
  GtkWidget *image746;
  GtkWidget *label131;
  GtkWidget *pkg_info_action_remove_button;
  GtkWidget *alignment28;
  GtkWidget *hbox79;
  GtkWidget *image747;
  GtkWidget *label132;
  GtkWidget *pkg_info_action_exclude_button;
  GtkWidget *alignment29;
  GtkWidget *hbox80;
  GtkWidget *image748;
  GtkWidget *label133;
  GtkWidget *pkg_action_label;
  GtkWidget *bottom_statusbar;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  gslapt = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (gslapt, "gslapt");
  gtk_window_set_title (GTK_WINDOW (gslapt), _("Gslapt"));
  gtk_window_set_default_size (GTK_WINDOW (gslapt), 600, 400);
  gtk_window_set_gravity (GTK_WINDOW (gslapt), GDK_GRAVITY_CENTER);

  gslapt_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (gslapt_vbox, "gslapt_vbox");
  gtk_widget_show (gslapt_vbox);
  gtk_container_add (GTK_CONTAINER (gslapt), gslapt_vbox);

  top_menubar = gtk_menu_bar_new ();
  gtk_widget_set_name (top_menubar, "top_menubar");
  gtk_widget_show (top_menubar);
  gtk_box_pack_start (GTK_BOX (gslapt_vbox), top_menubar, FALSE, FALSE, 0);

  actions2 = gtk_menu_item_new_with_mnemonic (_("_Actions"));
  gtk_widget_set_name (actions2, "actions2");
  gtk_widget_show (actions2);
  gtk_container_add (GTK_CONTAINER (top_menubar), actions2);

  actions2_menu = gtk_menu_new ();
  gtk_widget_set_name (actions2_menu, "actions2_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (actions2), actions2_menu);

  update2 = gtk_image_menu_item_new_with_mnemonic (_("_Update"));
  gtk_widget_set_name (update2, "update2");
  gtk_widget_show (update2);
  gtk_container_add (GTK_CONTAINER (actions2_menu), update2);
  gtk_widget_add_accelerator (update2, "activate", accel_group,
                              GDK_u, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image831 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image831, "image831");
  gtk_widget_show (image831);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (update2), image831);

  upgrade2 = gtk_image_menu_item_new_with_mnemonic (_("Up_grade"));
  gtk_widget_set_name (upgrade2, "upgrade2");
  gtk_widget_show (upgrade2);
  gtk_container_add (GTK_CONTAINER (actions2_menu), upgrade2);
  gtk_widget_add_accelerator (upgrade2, "activate", accel_group,
                              GDK_g, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image832 = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image832, "image832");
  gtk_widget_show (image832);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (upgrade2), image832);

  dist_upgrade2 = gtk_image_menu_item_new_with_mnemonic (_("_Dist-Upgrade"));
  gtk_widget_set_name (dist_upgrade2, "dist_upgrade2");
  gtk_widget_show (dist_upgrade2);
  gtk_container_add (GTK_CONTAINER (actions2_menu), dist_upgrade2);
  gtk_widget_add_accelerator (dist_upgrade2, "activate", accel_group,
                              GDK_d, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image833 = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image833, "image833");
  gtk_widget_show (image833);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (dist_upgrade2), image833);

  execute2 = gtk_image_menu_item_new_with_mnemonic (_("_Execute"));
  gtk_widget_set_name (execute2, "execute2");
  gtk_widget_show (execute2);
  gtk_container_add (GTK_CONTAINER (actions2_menu), execute2);
  gtk_widget_add_accelerator (execute2, "activate", accel_group,
                              GDK_e, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image834 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image834, "image834");
  gtk_widget_show (image834);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (execute2), image834);

  separator5 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separator5, "separator5");
  gtk_widget_show (separator5);
  gtk_container_add (GTK_CONTAINER (actions2_menu), separator5);
  gtk_widget_set_sensitive (separator5, FALSE);

  quit = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_set_name (quit, "quit");
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (actions2_menu), quit);

  settings1 = gtk_menu_item_new_with_mnemonic (_("_Settings"));
  gtk_widget_set_name (settings1, "settings1");
  gtk_widget_show (settings1);
  gtk_container_add (GTK_CONTAINER (top_menubar), settings1);

  settings1_menu = gtk_menu_new ();
  gtk_widget_set_name (settings1_menu, "settings1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (settings1), settings1_menu);

  preferences2 = gtk_image_menu_item_new_with_mnemonic (_("_Preferences"));
  gtk_widget_set_name (preferences2, "preferences2");
  gtk_widget_show (preferences2);
  gtk_container_add (GTK_CONTAINER (settings1_menu), preferences2);
  gtk_widget_add_accelerator (preferences2, "activate", accel_group,
                              GDK_p, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image835 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image835, "image835");
  gtk_widget_show (image835);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (preferences2), image835);

  help3 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_set_name (help3, "help3");
  gtk_widget_show (help3);
  gtk_container_add (GTK_CONTAINER (top_menubar), help3);

  help3_menu = gtk_menu_new ();
  gtk_widget_set_name (help3_menu, "help3_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help3), help3_menu);

  about3 = gtk_image_menu_item_new_with_mnemonic (_("About"));
  gtk_widget_set_name (about3, "about3");
  gtk_widget_show (about3);
  gtk_container_add (GTK_CONTAINER (help3_menu), about3);

  image836 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image836, "image836");
  gtk_widget_show (image836);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about3), image836);

  action_toolbar = gtk_toolbar_new ();
  gtk_widget_set_name (action_toolbar, "action_toolbar");
  gtk_widget_show (action_toolbar);
  gtk_box_pack_start (GTK_BOX (gslapt_vbox), action_toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (action_toolbar), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (action_toolbar));

  tmp_image = gtk_image_new_from_stock ("gtk-refresh", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  action_bar_update_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Update"));
  gtk_widget_set_name (action_bar_update_button, "action_bar_update_button");
  gtk_widget_show (action_bar_update_button);
  gtk_container_add (GTK_CONTAINER (action_toolbar), action_bar_update_button);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (action_bar_update_button), tooltips, _("Update local package cache"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-goto-top", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  action_bar_upgrade_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Upgrade All"));
  gtk_widget_set_name (action_bar_upgrade_button, "action_bar_upgrade_button");
  gtk_widget_show (action_bar_upgrade_button);
  gtk_container_add (GTK_CONTAINER (action_toolbar), action_bar_upgrade_button);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (action_bar_upgrade_button), tooltips, _("Upgrade installed packages"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-go-up", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  action_bar_dist_upgrade_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Dist-Upgrade"));
  gtk_widget_set_name (action_bar_dist_upgrade_button, "action_bar_dist_upgrade_button");
  gtk_widget_show (action_bar_dist_upgrade_button);
  gtk_container_add (GTK_CONTAINER (action_toolbar), action_bar_dist_upgrade_button);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (action_bar_dist_upgrade_button), tooltips, _("Upgrade to newer release"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-yes", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  action_bar_execute_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Execute"));
  gtk_widget_set_name (action_bar_execute_button, "action_bar_execute_button");
  gtk_widget_show (action_bar_execute_button);
  gtk_container_add (GTK_CONTAINER (action_toolbar), action_bar_execute_button);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (action_bar_execute_button), tooltips, _("Execute all scheduled actions in current transaction"), NULL);

  action_bar_quit_button = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-quit");
  gtk_widget_set_name (action_bar_quit_button, "action_bar_quit_button");
  gtk_widget_show (action_bar_quit_button);
  gtk_container_add (GTK_CONTAINER (action_toolbar), action_bar_quit_button);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (action_bar_quit_button), tooltips, _("Quit"), NULL);

  pkg_notebook_info_actionbox = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (pkg_notebook_info_actionbox, "pkg_notebook_info_actionbox");
  gtk_widget_show (pkg_notebook_info_actionbox);
  gtk_box_pack_start (GTK_BOX (gslapt_vbox), pkg_notebook_info_actionbox, TRUE, TRUE, 0);

  pkg_notebook = gtk_notebook_new ();
  gtk_widget_set_name (pkg_notebook, "pkg_notebook");
  gtk_widget_show (pkg_notebook);
  gtk_box_pack_start (GTK_BOX (pkg_notebook_info_actionbox), pkg_notebook, TRUE, TRUE, 0);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (pkg_notebook), TRUE);

  search_tab_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (search_tab_vbox, "search_tab_vbox");
  gtk_widget_show (search_tab_vbox);
  gtk_container_add (GTK_CONTAINER (pkg_notebook), search_tab_vbox);

  search_tab_search_align = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (search_tab_search_align, "search_tab_search_align");
  gtk_widget_show (search_tab_search_align);
  gtk_box_pack_start (GTK_BOX (search_tab_vbox), search_tab_search_align, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (search_tab_search_align), 1);

  search_tab_search_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (search_tab_search_hbox, "search_tab_search_hbox");
  gtk_widget_show (search_tab_search_hbox);
  gtk_container_add (GTK_CONTAINER (search_tab_search_align), search_tab_search_hbox);

  search_tab_search_entry = gtk_entry_new ();
  gtk_widget_set_name (search_tab_search_entry, "search_tab_search_entry");
  gtk_widget_show (search_tab_search_entry);
  gtk_box_pack_start (GTK_BOX (search_tab_search_hbox), search_tab_search_entry, TRUE, TRUE, 0);

  search_tab_search_button = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_set_name (search_tab_search_button, "search_tab_search_button");
  gtk_widget_show (search_tab_search_button);
  gtk_box_pack_start (GTK_BOX (search_tab_search_hbox), search_tab_search_button, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, search_tab_search_button, _("Search for expression"), NULL);

  search_tab_clear_button = gtk_button_new_with_mnemonic (_("Clear"));
  gtk_widget_set_name (search_tab_clear_button, "search_tab_clear_button");
  gtk_widget_show (search_tab_clear_button);
  gtk_box_pack_start (GTK_BOX (search_tab_search_hbox), search_tab_clear_button, FALSE, FALSE, 0);

  search_tab_search_results_scrolled = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (search_tab_search_results_scrolled, "search_tab_search_results_scrolled");
  gtk_widget_show (search_tab_search_results_scrolled);
  gtk_box_pack_start (GTK_BOX (search_tab_vbox), search_tab_search_results_scrolled, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (search_tab_search_results_scrolled), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  pkg_listing_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (pkg_listing_treeview, "pkg_listing_treeview");
  gtk_widget_show (pkg_listing_treeview);
  gtk_container_add (GTK_CONTAINER (search_tab_search_results_scrolled), pkg_listing_treeview);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (pkg_listing_treeview), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (pkg_listing_treeview), TRUE);

  search_tab = gtk_label_new_with_mnemonic (_("Packages"));
  gtk_widget_set_name (search_tab, "search_tab");
  gtk_widget_show (search_tab);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (pkg_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (pkg_notebook), 0), search_tab);

  pkg_info_action_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (pkg_info_action_hbox, "pkg_info_action_hbox");
  gtk_widget_show (pkg_info_action_hbox);
  gtk_box_pack_start (GTK_BOX (pkg_notebook_info_actionbox), pkg_info_action_hbox, TRUE, TRUE, 0);

  pkg_info_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (pkg_info_frame, "pkg_info_frame");
  gtk_widget_show (pkg_info_frame);
  gtk_box_pack_start (GTK_BOX (pkg_info_action_hbox), pkg_info_frame, TRUE, TRUE, 0);

  pkg_info_action_table = gtk_table_new (10, 2, FALSE);
  gtk_widget_set_name (pkg_info_action_table, "pkg_info_action_table");
  gtk_widget_show (pkg_info_action_table);
  gtk_container_add (GTK_CONTAINER (pkg_info_frame), pkg_info_action_table);
  gtk_container_set_border_width (GTK_CONTAINER (pkg_info_action_table), 1);
  gtk_table_set_row_spacings (GTK_TABLE (pkg_info_action_table), 2);
  gtk_table_set_col_spacings (GTK_TABLE (pkg_info_action_table), 2);

  pkg_info_action_name_label = gtk_label_new (_("Name"));
  gtk_widget_set_name (pkg_info_action_name_label, "pkg_info_action_name_label");
  gtk_widget_show (pkg_info_action_name_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_name_label, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_name_label), 0, 0.5);

  pkg_info_action_conflicts_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_conflicts_entry, "pkg_info_action_conflicts_entry");
  gtk_widget_show (pkg_info_action_conflicts_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_conflicts_entry, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_conflicts_entry), FALSE);

  pkg_info_action_mirror_label = gtk_label_new (_("Mirror"));
  gtk_widget_set_name (pkg_info_action_mirror_label, "pkg_info_action_mirror_label");
  gtk_widget_show (pkg_info_action_mirror_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_mirror_label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_mirror_label), 0, 0.5);

  pkg_info_action_location_label = gtk_label_new (_("Location"));
  gtk_widget_set_name (pkg_info_action_location_label, "pkg_info_action_location_label");
  gtk_widget_show (pkg_info_action_location_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_location_label, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_location_label), 0, 0.5);

  pkg_info_action_version_label = gtk_label_new (_("Version"));
  gtk_widget_set_name (pkg_info_action_version_label, "pkg_info_action_version_label");
  gtk_widget_show (pkg_info_action_version_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_version_label, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_version_label), 0, 0.5);

  pkg_info_action_size_label = gtk_label_new (_("Size"));
  gtk_widget_set_name (pkg_info_action_size_label, "pkg_info_action_size_label");
  gtk_widget_show (pkg_info_action_size_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_size_label, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_size_label), 0, 0.5);

  pkg_info_action_isize_label = gtk_label_new (_("Installed Size"));
  gtk_widget_set_name (pkg_info_action_isize_label, "pkg_info_action_isize_label");
  gtk_widget_show (pkg_info_action_isize_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_isize_label, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_isize_label), 0, 0.5);

  pkg_info_action_name_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_name_entry, "pkg_info_action_name_entry");
  gtk_widget_show (pkg_info_action_name_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_name_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_name_entry), FALSE);

  pkg_info_action_mirror_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_mirror_entry, "pkg_info_action_mirror_entry");
  gtk_widget_show (pkg_info_action_mirror_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_mirror_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_mirror_entry), FALSE);

  pkg_info_action_location_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_location_entry, "pkg_info_action_location_entry");
  gtk_widget_show (pkg_info_action_location_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_location_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_location_entry), FALSE);

  pkg_info_action_version_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_version_entry, "pkg_info_action_version_entry");
  gtk_widget_show (pkg_info_action_version_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_version_entry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_version_entry), FALSE);

  pkg_info_action_size_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_size_entry, "pkg_info_action_size_entry");
  gtk_widget_show (pkg_info_action_size_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_size_entry, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_size_entry), FALSE);

  pkg_info_action_isize_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_isize_entry, "pkg_info_action_isize_entry");
  gtk_widget_show (pkg_info_action_isize_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_isize_entry, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_isize_entry), FALSE);

  pkg_info_action_required_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_required_entry, "pkg_info_action_required_entry");
  gtk_widget_show (pkg_info_action_required_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_required_entry, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_required_entry), FALSE);

  pkg_info_action_description_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_description_entry, "pkg_info_action_description_entry");
  gtk_widget_show (pkg_info_action_description_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_description_entry, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_description_entry), FALSE);

  pkg_info_action_suggests_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_suggests_entry, "pkg_info_action_suggests_entry");
  gtk_widget_show (pkg_info_action_suggests_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_suggests_entry, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_suggests_entry), FALSE);

  pkg_info_action_description_label = gtk_label_new (_("Description"));
  gtk_widget_set_name (pkg_info_action_description_label, "pkg_info_action_description_label");
  gtk_widget_show (pkg_info_action_description_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_description_label, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_description_label), 0, 0.5);

  pkg_info_action_conflicts_label = gtk_label_new (_("Conflicts"));
  gtk_widget_set_name (pkg_info_action_conflicts_label, "pkg_info_action_conflicts_label");
  gtk_widget_show (pkg_info_action_conflicts_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_conflicts_label, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_conflicts_label), 0, 0.5);

  pkg_info_action_suggests_label = gtk_label_new (_("Suggests"));
  gtk_widget_set_name (pkg_info_action_suggests_label, "pkg_info_action_suggests_label");
  gtk_widget_show (pkg_info_action_suggests_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_suggests_label, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_suggests_label), 0, 0.5);

  pkg_info_action_required_label = gtk_label_new (_("Required"));
  gtk_widget_set_name (pkg_info_action_required_label, "pkg_info_action_required_label");
  gtk_widget_show (pkg_info_action_required_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_required_label, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_required_label), 0, 0.5);

  pkg_info_label = gtk_label_new (_("Package Information"));
  gtk_widget_set_name (pkg_info_label, "pkg_info_label");
  gtk_widget_show (pkg_info_label);
  gtk_frame_set_label_widget (GTK_FRAME (pkg_info_frame), pkg_info_label);

  pkg_action_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (pkg_action_frame, "pkg_action_frame");
  gtk_widget_show (pkg_action_frame);
  gtk_box_pack_start (GTK_BOX (pkg_info_action_hbox), pkg_action_frame, FALSE, TRUE, 0);

  pkg_action_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (pkg_action_vbox, "pkg_action_vbox");
  gtk_widget_show (pkg_action_vbox);
  gtk_container_add (GTK_CONTAINER (pkg_action_frame), pkg_action_vbox);

  pkg_info_action_install_upgrade_button = gtk_button_new ();
  gtk_widget_set_name (pkg_info_action_install_upgrade_button, "pkg_info_action_install_upgrade_button");
  gtk_widget_show (pkg_info_action_install_upgrade_button);
  gtk_box_pack_start (GTK_BOX (pkg_action_vbox), pkg_info_action_install_upgrade_button, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, pkg_info_action_install_upgrade_button, _("Install/Upgrade package"), NULL);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment27, "alignment27");
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (pkg_info_action_install_upgrade_button), alignment27);

  hbox78 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox78, "hbox78");
  gtk_widget_show (hbox78);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox78);

  image746 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image746, "image746");
  gtk_widget_show (image746);
  gtk_box_pack_start (GTK_BOX (hbox78), image746, FALSE, FALSE, 0);

  label131 = gtk_label_new_with_mnemonic (_("I_nstall/Upgrade"));
  gtk_widget_set_name (label131, "label131");
  gtk_widget_show (label131);
  gtk_box_pack_start (GTK_BOX (hbox78), label131, FALSE, FALSE, 0);

  pkg_info_action_remove_button = gtk_button_new ();
  gtk_widget_set_name (pkg_info_action_remove_button, "pkg_info_action_remove_button");
  gtk_widget_show (pkg_info_action_remove_button);
  gtk_box_pack_start (GTK_BOX (pkg_action_vbox), pkg_info_action_remove_button, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, pkg_info_action_remove_button, _("Remove package"), NULL);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment28, "alignment28");
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (pkg_info_action_remove_button), alignment28);

  hbox79 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox79, "hbox79");
  gtk_widget_show (hbox79);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox79);

  image747 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image747, "image747");
  gtk_widget_show (image747);
  gtk_box_pack_start (GTK_BOX (hbox79), image747, FALSE, FALSE, 0);

  label132 = gtk_label_new_with_mnemonic (_("_Remove"));
  gtk_widget_set_name (label132, "label132");
  gtk_widget_show (label132);
  gtk_box_pack_start (GTK_BOX (hbox79), label132, FALSE, FALSE, 0);

  pkg_info_action_exclude_button = gtk_button_new ();
  gtk_widget_set_name (pkg_info_action_exclude_button, "pkg_info_action_exclude_button");
  gtk_widget_show (pkg_info_action_exclude_button);
  gtk_box_pack_start (GTK_BOX (pkg_action_vbox), pkg_info_action_exclude_button, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, pkg_info_action_exclude_button, _("Exclude package"), NULL);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment29, "alignment29");
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (pkg_info_action_exclude_button), alignment29);

  hbox80 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox80, "hbox80");
  gtk_widget_show (hbox80);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox80);

  image748 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image748, "image748");
  gtk_widget_show (image748);
  gtk_box_pack_start (GTK_BOX (hbox80), image748, FALSE, FALSE, 0);

  label133 = gtk_label_new_with_mnemonic (_("E_xclude"));
  gtk_widget_set_name (label133, "label133");
  gtk_widget_show (label133);
  gtk_box_pack_start (GTK_BOX (hbox80), label133, FALSE, FALSE, 0);

  pkg_action_label = gtk_label_new (_("Package Action"));
  gtk_widget_set_name (pkg_action_label, "pkg_action_label");
  gtk_widget_show (pkg_action_label);
  gtk_frame_set_label_widget (GTK_FRAME (pkg_action_frame), pkg_action_label);

  bottom_statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (bottom_statusbar, "bottom_statusbar");
  gtk_widget_show (bottom_statusbar);
  gtk_box_pack_start (GTK_BOX (gslapt_vbox), bottom_statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) gslapt, "destroy",
                    G_CALLBACK (on_gslapt_destroy),
                    NULL);
  g_signal_connect ((gpointer) update2, "activate",
                    G_CALLBACK (update_callback),
                    NULL);
  g_signal_connect ((gpointer) upgrade2, "activate",
                    G_CALLBACK (upgrade_callback),
                    NULL);
  g_signal_connect ((gpointer) dist_upgrade2, "activate",
                    G_CALLBACK (distupgrade_callback),
                    NULL);
  g_signal_connect ((gpointer) execute2, "activate",
                    G_CALLBACK (execute_callback),
                    NULL);
  g_signal_connect ((gpointer) quit, "activate",
                    G_CALLBACK (quit_callback),
                    NULL);
  g_signal_connect ((gpointer) preferences2, "activate",
                    G_CALLBACK (open_preferences),
                    NULL);
  g_signal_connect ((gpointer) about3, "activate",
                    G_CALLBACK (open_about),
                    NULL);
  g_signal_connect ((gpointer) action_bar_update_button, "clicked",
                    G_CALLBACK (update_callback),
                    NULL);
  g_signal_connect ((gpointer) action_bar_upgrade_button, "clicked",
                    G_CALLBACK (upgrade_callback),
                    NULL);
  g_signal_connect ((gpointer) action_bar_dist_upgrade_button, "clicked",
                    G_CALLBACK (distupgrade_callback),
                    NULL);
  g_signal_connect ((gpointer) action_bar_execute_button, "clicked",
                    G_CALLBACK (execute_callback),
                    NULL);
  g_signal_connect ((gpointer) action_bar_quit_button, "clicked",
                    G_CALLBACK (quit_callback),
                    NULL);
  g_signal_connect ((gpointer) search_tab_search_button, "clicked",
                    G_CALLBACK (on_search_tab_search_button_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) search_tab_clear_button, "clicked",
                            G_CALLBACK (on_search_tab_clear_button_clicked),
                            GTK_OBJECT (search_tab_search_entry));
  g_signal_connect ((gpointer) pkg_info_action_install_upgrade_button, "clicked",
                    G_CALLBACK (add_pkg_for_install),
                    NULL);
  g_signal_connect ((gpointer) pkg_info_action_remove_button, "clicked",
                    G_CALLBACK (add_pkg_for_removal),
                    NULL);
  g_signal_connect ((gpointer) pkg_info_action_exclude_button, "clicked",
                    G_CALLBACK (add_pkg_for_exclude),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gslapt, gslapt, "gslapt");
  GLADE_HOOKUP_OBJECT (gslapt, gslapt_vbox, "gslapt_vbox");
  GLADE_HOOKUP_OBJECT (gslapt, top_menubar, "top_menubar");
  GLADE_HOOKUP_OBJECT (gslapt, actions2, "actions2");
  GLADE_HOOKUP_OBJECT (gslapt, actions2_menu, "actions2_menu");
  GLADE_HOOKUP_OBJECT (gslapt, update2, "update2");
  GLADE_HOOKUP_OBJECT (gslapt, image831, "image831");
  GLADE_HOOKUP_OBJECT (gslapt, upgrade2, "upgrade2");
  GLADE_HOOKUP_OBJECT (gslapt, image832, "image832");
  GLADE_HOOKUP_OBJECT (gslapt, dist_upgrade2, "dist_upgrade2");
  GLADE_HOOKUP_OBJECT (gslapt, image833, "image833");
  GLADE_HOOKUP_OBJECT (gslapt, execute2, "execute2");
  GLADE_HOOKUP_OBJECT (gslapt, image834, "image834");
  GLADE_HOOKUP_OBJECT (gslapt, separator5, "separator5");
  GLADE_HOOKUP_OBJECT (gslapt, quit, "quit");
  GLADE_HOOKUP_OBJECT (gslapt, settings1, "settings1");
  GLADE_HOOKUP_OBJECT (gslapt, settings1_menu, "settings1_menu");
  GLADE_HOOKUP_OBJECT (gslapt, preferences2, "preferences2");
  GLADE_HOOKUP_OBJECT (gslapt, image835, "image835");
  GLADE_HOOKUP_OBJECT (gslapt, help3, "help3");
  GLADE_HOOKUP_OBJECT (gslapt, help3_menu, "help3_menu");
  GLADE_HOOKUP_OBJECT (gslapt, about3, "about3");
  GLADE_HOOKUP_OBJECT (gslapt, image836, "image836");
  GLADE_HOOKUP_OBJECT (gslapt, action_toolbar, "action_toolbar");
  GLADE_HOOKUP_OBJECT (gslapt, action_bar_update_button, "action_bar_update_button");
  GLADE_HOOKUP_OBJECT (gslapt, action_bar_upgrade_button, "action_bar_upgrade_button");
  GLADE_HOOKUP_OBJECT (gslapt, action_bar_dist_upgrade_button, "action_bar_dist_upgrade_button");
  GLADE_HOOKUP_OBJECT (gslapt, action_bar_execute_button, "action_bar_execute_button");
  GLADE_HOOKUP_OBJECT (gslapt, action_bar_quit_button, "action_bar_quit_button");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_notebook_info_actionbox, "pkg_notebook_info_actionbox");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_notebook, "pkg_notebook");
  GLADE_HOOKUP_OBJECT (gslapt, search_tab_vbox, "search_tab_vbox");
  GLADE_HOOKUP_OBJECT (gslapt, search_tab_search_align, "search_tab_search_align");
  GLADE_HOOKUP_OBJECT (gslapt, search_tab_search_hbox, "search_tab_search_hbox");
  GLADE_HOOKUP_OBJECT (gslapt, search_tab_search_entry, "search_tab_search_entry");
  GLADE_HOOKUP_OBJECT (gslapt, search_tab_search_button, "search_tab_search_button");
  GLADE_HOOKUP_OBJECT (gslapt, search_tab_clear_button, "search_tab_clear_button");
  GLADE_HOOKUP_OBJECT (gslapt, search_tab_search_results_scrolled, "search_tab_search_results_scrolled");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_listing_treeview, "pkg_listing_treeview");
  GLADE_HOOKUP_OBJECT (gslapt, search_tab, "search_tab");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_hbox, "pkg_info_action_hbox");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_frame, "pkg_info_frame");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_table, "pkg_info_action_table");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_name_label, "pkg_info_action_name_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_conflicts_entry, "pkg_info_action_conflicts_entry");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_mirror_label, "pkg_info_action_mirror_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_location_label, "pkg_info_action_location_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_version_label, "pkg_info_action_version_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_size_label, "pkg_info_action_size_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_isize_label, "pkg_info_action_isize_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_name_entry, "pkg_info_action_name_entry");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_mirror_entry, "pkg_info_action_mirror_entry");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_location_entry, "pkg_info_action_location_entry");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_version_entry, "pkg_info_action_version_entry");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_size_entry, "pkg_info_action_size_entry");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_isize_entry, "pkg_info_action_isize_entry");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_required_entry, "pkg_info_action_required_entry");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_description_entry, "pkg_info_action_description_entry");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_suggests_entry, "pkg_info_action_suggests_entry");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_description_label, "pkg_info_action_description_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_conflicts_label, "pkg_info_action_conflicts_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_suggests_label, "pkg_info_action_suggests_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_required_label, "pkg_info_action_required_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_label, "pkg_info_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_action_frame, "pkg_action_frame");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_action_vbox, "pkg_action_vbox");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_install_upgrade_button, "pkg_info_action_install_upgrade_button");
  GLADE_HOOKUP_OBJECT (gslapt, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (gslapt, hbox78, "hbox78");
  GLADE_HOOKUP_OBJECT (gslapt, image746, "image746");
  GLADE_HOOKUP_OBJECT (gslapt, label131, "label131");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_remove_button, "pkg_info_action_remove_button");
  GLADE_HOOKUP_OBJECT (gslapt, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (gslapt, hbox79, "hbox79");
  GLADE_HOOKUP_OBJECT (gslapt, image747, "image747");
  GLADE_HOOKUP_OBJECT (gslapt, label132, "label132");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_exclude_button, "pkg_info_action_exclude_button");
  GLADE_HOOKUP_OBJECT (gslapt, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (gslapt, hbox80, "hbox80");
  GLADE_HOOKUP_OBJECT (gslapt, image748, "image748");
  GLADE_HOOKUP_OBJECT (gslapt, label133, "label133");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_action_label, "pkg_action_label");
  GLADE_HOOKUP_OBJECT (gslapt, bottom_statusbar, "bottom_statusbar");
  GLADE_HOOKUP_OBJECT_NO_REF (gslapt, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (gslapt), accel_group);

  return gslapt;
}

GtkWidget*
create_about (void)
{
  GtkWidget *about;
  GtkWidget *dialog_vbox1;
  GtkWidget *image797;
  GtkWidget *label138;
  GtkWidget *label137;
  GtkWidget *dialog_action_area1;
  GtkWidget *closebutton1;

  about = gtk_dialog_new ();
  gtk_widget_set_name (about, "about");
  gtk_window_set_title (GTK_WINDOW (about), _("About Gslapt"));
  gtk_window_set_type_hint (GTK_WINDOW (about), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (about)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_widget_show (dialog_vbox1);

  image797 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_DIALOG);
  gtk_widget_set_name (image797, "image797");
  gtk_widget_show (image797);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), image797, FALSE, FALSE, 0);

  label138 = gtk_label_new ("");
  gtk_widget_set_name (label138, "label138");
  gtk_widget_show (label138);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label138, FALSE, FALSE, 0);

  label137 = gtk_label_new (_("               Gslapt\n\n        GTK+ slapt-get \n\nCopyright Jason Woodward"));
  gtk_widget_set_name (label137, "label137");
  gtk_widget_show (label137);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label137, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (about)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (closebutton1, "closebutton1");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (about), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) about, "close",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (about));
  g_signal_connect_swapped ((gpointer) about, "destroy_event",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (about));
  g_signal_connect_swapped ((gpointer) closebutton1, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (about));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about, about, "about");
  GLADE_HOOKUP_OBJECT_NO_REF (about, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (about, image797, "image797");
  GLADE_HOOKUP_OBJECT (about, label138, "label138");
  GLADE_HOOKUP_OBJECT (about, label137, "label137");
  GLADE_HOOKUP_OBJECT_NO_REF (about, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (about, closebutton1, "closebutton1");

  return about;
}

