/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_preferences (void)
{
  GtkWidget *window_preferences;
  GdkPixbuf *window_preferences_icon_pixbuf;
  GtkWidget *preferences_vbox;
  GtkWidget *preferences_notebook;
  GtkWidget *preferences_working_dir_vbox;
  GtkWidget *preferences_working_dir_vbox_vbox;
  GtkWidget *preferences_working_dir_label;
  GtkWidget *hbox3;
  GtkWidget *label72;
  GtkWidget *vbox12;
  GtkWidget *preferences_working_dir_entry;
  GtkWidget *label50;
  GtkWidget *preferences_sources_vbox;
  GtkWidget *vbox57;
  GtkWidget *label161;
  GtkWidget *hbox92;
  GtkWidget *label162;
  GtkWidget *hbox93;
  GtkWidget *scrolledwindow16;
  GtkWidget *preferences_sources_treeview;
  GtkWidget *vbox58;
  GtkWidget *preferences_remove_source_button;
  GtkWidget *hbox94;
  GtkWidget *label163;
  GtkWidget *new_source_entry;
  GtkWidget *preferences_add_source_button;
  GtkWidget *label160;
  GtkWidget *preferences_exclude_vbox;
  GtkWidget *preferences_exclude_vbox_vbox;
  GtkWidget *preferences_exclude_label;
  GtkWidget *hbox81;
  GtkWidget *label140;
  GtkWidget *hbox82;
  GtkWidget *scrolledwindow12;
  GtkWidget *preferences_exclude_treeview;
  GtkWidget *vbox42;
  GtkWidget *preferences_remove_exclude_button;
  GtkWidget *hbox95;
  GtkWidget *label164;
  GtkWidget *new_exclude_entry;
  GtkWidget *preferences_add_exclude_button;
  GtkWidget *label51;
  GtkWidget *preferences_hbuttonbox;
  GtkWidget *preferences_close_button;
  GtkWidget *preferences_ok_button;

  window_preferences = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window_preferences, "window_preferences");
  gtk_window_set_title (GTK_WINDOW (window_preferences), _("Preferences"));
  gtk_window_set_position (GTK_WINDOW (window_preferences), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (window_preferences), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (window_preferences), 400, 300);
  window_preferences_icon_pixbuf = create_pixbuf ("gslapt.png");
  if (window_preferences_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window_preferences), window_preferences_icon_pixbuf);
      gdk_pixbuf_unref (window_preferences_icon_pixbuf);
    }
  gtk_window_set_gravity (GTK_WINDOW (window_preferences), GDK_GRAVITY_CENTER);

  preferences_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (preferences_vbox, "preferences_vbox");
  gtk_widget_show (preferences_vbox);
  gtk_container_add (GTK_CONTAINER (window_preferences), preferences_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_vbox), 6);

  preferences_notebook = gtk_notebook_new ();
  gtk_widget_set_name (preferences_notebook, "preferences_notebook");
  gtk_widget_show (preferences_notebook);
  gtk_box_pack_start (GTK_BOX (preferences_vbox), preferences_notebook, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_notebook), 6);

  preferences_working_dir_vbox = gtk_vbox_new (FALSE, 18);
  gtk_widget_set_name (preferences_working_dir_vbox, "preferences_working_dir_vbox");
  gtk_widget_show (preferences_working_dir_vbox);
  gtk_container_add (GTK_CONTAINER (preferences_notebook), preferences_working_dir_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_working_dir_vbox), 12);

  preferences_working_dir_vbox_vbox = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (preferences_working_dir_vbox_vbox, "preferences_working_dir_vbox_vbox");
  gtk_widget_show (preferences_working_dir_vbox_vbox);
  gtk_box_pack_start (GTK_BOX (preferences_working_dir_vbox), preferences_working_dir_vbox_vbox, TRUE, TRUE, 0);

  preferences_working_dir_label = gtk_label_new (_("<b>Package and data storage</b>"));
  gtk_widget_set_name (preferences_working_dir_label, "preferences_working_dir_label");
  gtk_widget_show (preferences_working_dir_label);
  gtk_box_pack_start (GTK_BOX (preferences_working_dir_vbox_vbox), preferences_working_dir_label, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (preferences_working_dir_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (preferences_working_dir_label), 0, 0.5);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (preferences_working_dir_vbox_vbox), hbox3, TRUE, TRUE, 0);

  label72 = gtk_label_new ("    ");
  gtk_widget_set_name (label72, "label72");
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox3), label72, FALSE, FALSE, 0);

  vbox12 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox12, "vbox12");
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox12, FALSE, FALSE, 0);

  preferences_working_dir_entry = gtk_entry_new ();
  gtk_widget_set_name (preferences_working_dir_entry, "preferences_working_dir_entry");
  gtk_widget_show (preferences_working_dir_entry);
  gtk_box_pack_start (GTK_BOX (vbox12), preferences_working_dir_entry, FALSE, FALSE, 0);

  label50 = gtk_label_new (_("Working Directory"));
  gtk_widget_set_name (label50, "label50");
  gtk_widget_show (label50);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (preferences_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (preferences_notebook), 0), label50);
  gtk_label_set_justify (GTK_LABEL (label50), GTK_JUSTIFY_CENTER);

  preferences_sources_vbox = gtk_vbox_new (FALSE, 18);
  gtk_widget_set_name (preferences_sources_vbox, "preferences_sources_vbox");
  gtk_widget_show (preferences_sources_vbox);
  gtk_container_add (GTK_CONTAINER (preferences_notebook), preferences_sources_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_sources_vbox), 12);

  vbox57 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox57, "vbox57");
  gtk_widget_show (vbox57);
  gtk_box_pack_start (GTK_BOX (preferences_sources_vbox), vbox57, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox57), 12);

  label161 = gtk_label_new (_("<b>Package Sources</b>"));
  gtk_widget_set_name (label161, "label161");
  gtk_widget_show (label161);
  gtk_box_pack_start (GTK_BOX (vbox57), label161, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label161), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label161), 0, 0.5);

  hbox92 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox92, "hbox92");
  gtk_widget_show (hbox92);
  gtk_box_pack_start (GTK_BOX (vbox57), hbox92, TRUE, TRUE, 0);
  gtk_widget_set_size_request (hbox92, -1, 174);

  label162 = gtk_label_new ("    ");
  gtk_widget_set_name (label162, "label162");
  gtk_widget_show (label162);
  gtk_box_pack_start (GTK_BOX (hbox92), label162, FALSE, FALSE, 0);

  hbox93 = gtk_hbox_new (FALSE, 12);
  gtk_widget_set_name (hbox93, "hbox93");
  gtk_widget_show (hbox93);
  gtk_box_pack_start (GTK_BOX (hbox92), hbox93, TRUE, TRUE, 0);

  scrolledwindow16 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow16, "scrolledwindow16");
  gtk_widget_show (scrolledwindow16);
  gtk_box_pack_start (GTK_BOX (hbox93), scrolledwindow16, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow16), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow16), GTK_SHADOW_IN);

  preferences_sources_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (preferences_sources_treeview, "preferences_sources_treeview");
  gtk_widget_show (preferences_sources_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow16), preferences_sources_treeview);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (preferences_sources_treeview), FALSE);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (preferences_sources_treeview), TRUE);

  vbox58 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox58, "vbox58");
  gtk_widget_show (vbox58);
  gtk_box_pack_start (GTK_BOX (hbox93), vbox58, FALSE, FALSE, 0);

  preferences_remove_source_button = gtk_button_new_from_stock ("gtk-remove");
  gtk_widget_set_name (preferences_remove_source_button, "preferences_remove_source_button");
  gtk_widget_show (preferences_remove_source_button);
  gtk_box_pack_start (GTK_BOX (vbox58), preferences_remove_source_button, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (preferences_remove_source_button, GTK_CAN_DEFAULT);

  hbox94 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox94, "hbox94");
  gtk_widget_show (hbox94);
  gtk_box_pack_start (GTK_BOX (vbox57), hbox94, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox94), 6);

  label163 = gtk_label_new (_("<span weight=\"bold\">SOURCE=</span>"));
  gtk_widget_set_name (label163, "label163");
  gtk_widget_show (label163);
  gtk_box_pack_start (GTK_BOX (hbox94), label163, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label163), TRUE);

  new_source_entry = gtk_entry_new ();
  gtk_widget_set_name (new_source_entry, "new_source_entry");
  gtk_widget_show (new_source_entry);
  gtk_box_pack_start (GTK_BOX (hbox94), new_source_entry, TRUE, TRUE, 0);

  preferences_add_source_button = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_set_name (preferences_add_source_button, "preferences_add_source_button");
  gtk_widget_show (preferences_add_source_button);
  gtk_box_pack_start (GTK_BOX (hbox94), preferences_add_source_button, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (preferences_add_source_button, GTK_CAN_DEFAULT);

  label160 = gtk_label_new (_("Sources"));
  gtk_widget_set_name (label160, "label160");
  gtk_widget_show (label160);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (preferences_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (preferences_notebook), 1), label160);

  preferences_exclude_vbox = gtk_vbox_new (FALSE, 18);
  gtk_widget_set_name (preferences_exclude_vbox, "preferences_exclude_vbox");
  gtk_widget_show (preferences_exclude_vbox);
  gtk_container_add (GTK_CONTAINER (preferences_notebook), preferences_exclude_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_exclude_vbox), 12);

  preferences_exclude_vbox_vbox = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (preferences_exclude_vbox_vbox, "preferences_exclude_vbox_vbox");
  gtk_widget_show (preferences_exclude_vbox_vbox);
  gtk_box_pack_start (GTK_BOX (preferences_exclude_vbox), preferences_exclude_vbox_vbox, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_exclude_vbox_vbox), 12);

  preferences_exclude_label = gtk_label_new (_("<b>Exclude List</b>"));
  gtk_widget_set_name (preferences_exclude_label, "preferences_exclude_label");
  gtk_widget_show (preferences_exclude_label);
  gtk_box_pack_start (GTK_BOX (preferences_exclude_vbox_vbox), preferences_exclude_label, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (preferences_exclude_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (preferences_exclude_label), 0, 0.5);

  hbox81 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox81, "hbox81");
  gtk_widget_show (hbox81);
  gtk_box_pack_start (GTK_BOX (preferences_exclude_vbox_vbox), hbox81, TRUE, TRUE, 0);
  gtk_widget_set_size_request (hbox81, -1, 174);

  label140 = gtk_label_new ("    ");
  gtk_widget_set_name (label140, "label140");
  gtk_widget_show (label140);
  gtk_box_pack_start (GTK_BOX (hbox81), label140, FALSE, FALSE, 0);

  hbox82 = gtk_hbox_new (FALSE, 12);
  gtk_widget_set_name (hbox82, "hbox82");
  gtk_widget_show (hbox82);
  gtk_box_pack_start (GTK_BOX (hbox81), hbox82, TRUE, TRUE, 0);

  scrolledwindow12 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow12, "scrolledwindow12");
  gtk_widget_show (scrolledwindow12);
  gtk_box_pack_start (GTK_BOX (hbox82), scrolledwindow12, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow12), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow12), GTK_SHADOW_IN);

  preferences_exclude_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (preferences_exclude_treeview, "preferences_exclude_treeview");
  gtk_widget_show (preferences_exclude_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow12), preferences_exclude_treeview);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (preferences_exclude_treeview), FALSE);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (preferences_exclude_treeview), TRUE);

  vbox42 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox42, "vbox42");
  gtk_widget_show (vbox42);
  gtk_box_pack_start (GTK_BOX (hbox82), vbox42, FALSE, FALSE, 0);

  preferences_remove_exclude_button = gtk_button_new_from_stock ("gtk-remove");
  gtk_widget_set_name (preferences_remove_exclude_button, "preferences_remove_exclude_button");
  gtk_widget_show (preferences_remove_exclude_button);
  gtk_box_pack_start (GTK_BOX (vbox42), preferences_remove_exclude_button, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (preferences_remove_exclude_button, GTK_CAN_DEFAULT);

  hbox95 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox95, "hbox95");
  gtk_widget_show (hbox95);
  gtk_box_pack_start (GTK_BOX (preferences_exclude_vbox_vbox), hbox95, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox95), 6);

  label164 = gtk_label_new (_("<span weight=\"bold\">Exclude Expression:</span>"));
  gtk_widget_set_name (label164, "label164");
  gtk_widget_show (label164);
  gtk_box_pack_start (GTK_BOX (hbox95), label164, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label164), TRUE);

  new_exclude_entry = gtk_entry_new ();
  gtk_widget_set_name (new_exclude_entry, "new_exclude_entry");
  gtk_widget_show (new_exclude_entry);
  gtk_box_pack_start (GTK_BOX (hbox95), new_exclude_entry, TRUE, TRUE, 0);

  preferences_add_exclude_button = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_set_name (preferences_add_exclude_button, "preferences_add_exclude_button");
  gtk_widget_show (preferences_add_exclude_button);
  gtk_box_pack_start (GTK_BOX (hbox95), preferences_add_exclude_button, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (preferences_add_exclude_button, GTK_CAN_DEFAULT);

  label51 = gtk_label_new (_("Excludes"));
  gtk_widget_set_name (label51, "label51");
  gtk_widget_show (label51);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (preferences_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (preferences_notebook), 2), label51);
  gtk_label_set_justify (GTK_LABEL (label51), GTK_JUSTIFY_CENTER);

  preferences_hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_set_name (preferences_hbuttonbox, "preferences_hbuttonbox");
  gtk_widget_show (preferences_hbuttonbox);
  gtk_box_pack_start (GTK_BOX (preferences_vbox), preferences_hbuttonbox, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (preferences_hbuttonbox), 6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (preferences_hbuttonbox), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (preferences_hbuttonbox), 6);

  preferences_close_button = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (preferences_close_button, "preferences_close_button");
  gtk_widget_show (preferences_close_button);
  gtk_container_add (GTK_CONTAINER (preferences_hbuttonbox), preferences_close_button);
  GTK_WIDGET_SET_FLAGS (preferences_close_button, GTK_CAN_DEFAULT);

  preferences_ok_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (preferences_ok_button, "preferences_ok_button");
  gtk_widget_show (preferences_ok_button);
  gtk_container_add (GTK_CONTAINER (preferences_hbuttonbox), preferences_ok_button);
  GTK_WIDGET_SET_FLAGS (preferences_ok_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) window_preferences, "destroy_event",
                    G_CALLBACK (gtk_widget_destroy),
                    NULL);
  g_signal_connect_swapped ((gpointer) preferences_remove_source_button, "clicked",
                            G_CALLBACK (preferences_sources_remove),
                            GTK_OBJECT (window_preferences));
  g_signal_connect_swapped ((gpointer) preferences_add_source_button, "clicked",
                            G_CALLBACK (preferences_sources_add),
                            GTK_OBJECT (window_preferences));
  g_signal_connect_swapped ((gpointer) preferences_remove_exclude_button, "clicked",
                            G_CALLBACK (preferences_exclude_remove),
                            GTK_OBJECT (window_preferences));
  g_signal_connect_swapped ((gpointer) preferences_add_exclude_button, "clicked",
                            G_CALLBACK (preferences_exclude_add),
                            GTK_OBJECT (window_preferences));
  g_signal_connect_swapped ((gpointer) preferences_close_button, "clicked",
                            G_CALLBACK (cancel_preferences),
                            GTK_OBJECT (window_preferences));
  g_signal_connect_swapped ((gpointer) preferences_ok_button, "clicked",
                            G_CALLBACK (preferences_on_ok_clicked),
                            GTK_OBJECT (window_preferences));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_preferences, window_preferences, "window_preferences");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_vbox, "preferences_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_notebook, "preferences_notebook");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_working_dir_vbox, "preferences_working_dir_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_working_dir_vbox_vbox, "preferences_working_dir_vbox_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_working_dir_label, "preferences_working_dir_label");
  GLADE_HOOKUP_OBJECT (window_preferences, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_preferences, label72, "label72");
  GLADE_HOOKUP_OBJECT (window_preferences, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_working_dir_entry, "preferences_working_dir_entry");
  GLADE_HOOKUP_OBJECT (window_preferences, label50, "label50");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_sources_vbox, "preferences_sources_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, vbox57, "vbox57");
  GLADE_HOOKUP_OBJECT (window_preferences, label161, "label161");
  GLADE_HOOKUP_OBJECT (window_preferences, hbox92, "hbox92");
  GLADE_HOOKUP_OBJECT (window_preferences, label162, "label162");
  GLADE_HOOKUP_OBJECT (window_preferences, hbox93, "hbox93");
  GLADE_HOOKUP_OBJECT (window_preferences, scrolledwindow16, "scrolledwindow16");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_sources_treeview, "preferences_sources_treeview");
  GLADE_HOOKUP_OBJECT (window_preferences, vbox58, "vbox58");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_remove_source_button, "preferences_remove_source_button");
  GLADE_HOOKUP_OBJECT (window_preferences, hbox94, "hbox94");
  GLADE_HOOKUP_OBJECT (window_preferences, label163, "label163");
  GLADE_HOOKUP_OBJECT (window_preferences, new_source_entry, "new_source_entry");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_add_source_button, "preferences_add_source_button");
  GLADE_HOOKUP_OBJECT (window_preferences, label160, "label160");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_exclude_vbox, "preferences_exclude_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_exclude_vbox_vbox, "preferences_exclude_vbox_vbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_exclude_label, "preferences_exclude_label");
  GLADE_HOOKUP_OBJECT (window_preferences, hbox81, "hbox81");
  GLADE_HOOKUP_OBJECT (window_preferences, label140, "label140");
  GLADE_HOOKUP_OBJECT (window_preferences, hbox82, "hbox82");
  GLADE_HOOKUP_OBJECT (window_preferences, scrolledwindow12, "scrolledwindow12");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_exclude_treeview, "preferences_exclude_treeview");
  GLADE_HOOKUP_OBJECT (window_preferences, vbox42, "vbox42");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_remove_exclude_button, "preferences_remove_exclude_button");
  GLADE_HOOKUP_OBJECT (window_preferences, hbox95, "hbox95");
  GLADE_HOOKUP_OBJECT (window_preferences, label164, "label164");
  GLADE_HOOKUP_OBJECT (window_preferences, new_exclude_entry, "new_exclude_entry");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_add_exclude_button, "preferences_add_exclude_button");
  GLADE_HOOKUP_OBJECT (window_preferences, label51, "label51");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_hbuttonbox, "preferences_hbuttonbox");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_close_button, "preferences_close_button");
  GLADE_HOOKUP_OBJECT (window_preferences, preferences_ok_button, "preferences_ok_button");

  return window_preferences;
}

GtkWidget*
create_gslapt (void)
{
  GtkWidget *gslapt;
  GdkPixbuf *gslapt_icon_pixbuf;
  GtkWidget *gslapt_vbox;
  GtkWidget *top_menubar;
  GtkWidget *actions2;
  GtkWidget *actions2_menu;
  GtkWidget *quit;
  GtkWidget *settings1;
  GtkWidget *settings1_menu;
  GtkWidget *preferences2;
  GtkWidget *image863;
  GtkWidget *help3;
  GtkWidget *help3_menu;
  GtkWidget *about3;
  GtkWidget *image864;
  GtkWidget *action_toolbar;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *action_bar_update_button;
  GtkWidget *action_bar_upgrade_button;
  GtkWidget *action_bar_clean_button;
  GtkWidget *separatortoolitem1;
  GtkWidget *action_bar_execute_button;
  GtkWidget *search_vbox;
  GtkWidget *search_align;
  GtkWidget *search_hbox;
  GtkWidget *search_entry;
  GtkWidget *search_button;
  GtkWidget *clear_button;
  GtkWidget *pkg_vpaned;
  GtkWidget *pkg_list_scrolled;
  GtkWidget *pkg_listing_treeview;
  GtkWidget *pkg_info_action_hbox;
  GtkWidget *pkg_info_notebook;
  GtkWidget *scrolledwindow20;
  GtkWidget *viewport1;
  GtkWidget *vbox63;
  GtkWidget *table2;
  GtkWidget *label226;
  GtkWidget *label227;
  GtkWidget *label244;
  GtkWidget *pkg_info_name;
  GtkWidget *pkg_info_description;
  GtkWidget *pkg_info_location;
  GtkWidget *table3;
  GtkWidget *label237;
  GtkWidget *label238;
  GtkWidget *label239;
  GtkWidget *label245;
  GtkWidget *pkg_info_version;
  GtkWidget *pkg_info_size;
  GtkWidget *pkg_info_installed_size;
  GtkWidget *pkg_info_mirror;
  GtkWidget *pkg_info_common_label;
  GtkWidget *vbox64;
  GtkWidget *scrolledwindow19;
  GtkWidget *pkg_description_textview;
  GtkWidget *pkg_info_description_label;
  GtkWidget *scrolledwindow21;
  GtkWidget *viewport2;
  GtkWidget *pkg_info_dep_vbox;
  GtkWidget *table4;
  GtkWidget *label247;
  GtkWidget *label248;
  GtkWidget *label249;
  GtkWidget *pkg_info_required;
  GtkWidget *pkg_info_conflicts;
  GtkWidget *pkg_info_suggests;
  GtkWidget *pkg_info_dependencies_label;
  GtkWidget *pkg_action_vbox;
  GtkWidget *label246;
  GtkWidget *pkg_info_action_install_upgrade_button;
  GtkWidget *alignment27;
  GtkWidget *hbox78;
  GtkWidget *image746;
  GtkWidget *label131;
  GtkWidget *pkg_info_action_remove_button;
  GtkWidget *alignment28;
  GtkWidget *hbox79;
  GtkWidget *image747;
  GtkWidget *label132;
  GtkWidget *bottom_statusbar;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  gslapt = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (gslapt, "gslapt");
  gtk_window_set_title (GTK_WINDOW (gslapt), _("Gslapt"));
  gtk_window_set_position (GTK_WINDOW (gslapt), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (gslapt), 640, 480);
  gslapt_icon_pixbuf = create_pixbuf ("gslapt.png");
  if (gslapt_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (gslapt), gslapt_icon_pixbuf);
      gdk_pixbuf_unref (gslapt_icon_pixbuf);
    }
  gtk_window_set_gravity (GTK_WINDOW (gslapt), GDK_GRAVITY_CENTER);

  gslapt_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (gslapt_vbox, "gslapt_vbox");
  gtk_widget_show (gslapt_vbox);
  gtk_container_add (GTK_CONTAINER (gslapt), gslapt_vbox);

  top_menubar = gtk_menu_bar_new ();
  gtk_widget_set_name (top_menubar, "top_menubar");
  gtk_widget_show (top_menubar);
  gtk_box_pack_start (GTK_BOX (gslapt_vbox), top_menubar, FALSE, FALSE, 0);

  actions2 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_set_name (actions2, "actions2");
  gtk_widget_show (actions2);
  gtk_container_add (GTK_CONTAINER (top_menubar), actions2);

  actions2_menu = gtk_menu_new ();
  gtk_widget_set_name (actions2_menu, "actions2_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (actions2), actions2_menu);

  quit = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_set_name (quit, "quit");
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (actions2_menu), quit);

  settings1 = gtk_menu_item_new_with_mnemonic (_("_Settings"));
  gtk_widget_set_name (settings1, "settings1");
  gtk_widget_show (settings1);
  gtk_container_add (GTK_CONTAINER (top_menubar), settings1);

  settings1_menu = gtk_menu_new ();
  gtk_widget_set_name (settings1_menu, "settings1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (settings1), settings1_menu);

  preferences2 = gtk_image_menu_item_new_with_mnemonic (_("_Preferences"));
  gtk_widget_set_name (preferences2, "preferences2");
  gtk_widget_show (preferences2);
  gtk_container_add (GTK_CONTAINER (settings1_menu), preferences2);
  gtk_widget_add_accelerator (preferences2, "activate", accel_group,
                              GDK_p, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image863 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image863, "image863");
  gtk_widget_show (image863);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (preferences2), image863);

  help3 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_set_name (help3, "help3");
  gtk_widget_show (help3);
  gtk_container_add (GTK_CONTAINER (top_menubar), help3);

  help3_menu = gtk_menu_new ();
  gtk_widget_set_name (help3_menu, "help3_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help3), help3_menu);

  about3 = gtk_image_menu_item_new_with_mnemonic (_("About"));
  gtk_widget_set_name (about3, "about3");
  gtk_widget_show (about3);
  gtk_container_add (GTK_CONTAINER (help3_menu), about3);

  image864 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image864, "image864");
  gtk_widget_show (image864);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about3), image864);

  action_toolbar = gtk_toolbar_new ();
  gtk_widget_set_name (action_toolbar, "action_toolbar");
  gtk_widget_show (action_toolbar);
  gtk_box_pack_start (GTK_BOX (gslapt_vbox), action_toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (action_toolbar), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (action_toolbar));

  tmp_image = gtk_image_new_from_stock ("gtk-refresh", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  action_bar_update_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Update"));
  gtk_widget_set_name (action_bar_update_button, "action_bar_update_button");
  gtk_widget_show (action_bar_update_button);
  gtk_container_add (GTK_CONTAINER (action_toolbar), action_bar_update_button);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (action_bar_update_button), tooltips, _("Update local package cache"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-goto-top", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  action_bar_upgrade_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Upgrade All"));
  gtk_widget_set_name (action_bar_upgrade_button, "action_bar_upgrade_button");
  gtk_widget_show (action_bar_upgrade_button);
  gtk_container_add (GTK_CONTAINER (action_toolbar), action_bar_upgrade_button);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (action_bar_upgrade_button), tooltips, _("Upgrade installed packages"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-clear", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  action_bar_clean_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Clean"));
  gtk_widget_set_name (action_bar_clean_button, "action_bar_clean_button");
  gtk_widget_show (action_bar_clean_button);
  gtk_container_add (GTK_CONTAINER (action_toolbar), action_bar_clean_button);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (action_bar_clean_button), tooltips, _("Clean archived packages off filesystem"), NULL);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_set_name (separatortoolitem1, "separatortoolitem1");
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (action_toolbar), separatortoolitem1);

  tmp_image = gtk_image_new_from_stock ("gtk-yes", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  action_bar_execute_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Execute"));
  gtk_widget_set_name (action_bar_execute_button, "action_bar_execute_button");
  gtk_widget_show (action_bar_execute_button);
  gtk_container_add (GTK_CONTAINER (action_toolbar), action_bar_execute_button);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (action_bar_execute_button), tooltips, _("Execute all scheduled actions in current transaction"), NULL);

  search_vbox = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (search_vbox, "search_vbox");
  gtk_widget_show (search_vbox);
  gtk_box_pack_start (GTK_BOX (gslapt_vbox), search_vbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (search_vbox), 6);

  search_align = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (search_align, "search_align");
  gtk_widget_show (search_align);
  gtk_box_pack_start (GTK_BOX (search_vbox), search_align, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (search_align), 1);

  search_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (search_hbox, "search_hbox");
  gtk_widget_show (search_hbox);
  gtk_container_add (GTK_CONTAINER (search_align), search_hbox);

  search_entry = gtk_entry_new ();
  gtk_widget_set_name (search_entry, "search_entry");
  gtk_widget_show (search_entry);
  gtk_box_pack_start (GTK_BOX (search_hbox), search_entry, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (search_entry, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (search_entry, "grab_focus", accel_group,
                              GDK_L, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  search_button = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_set_name (search_button, "search_button");
  gtk_widget_show (search_button);
  gtk_box_pack_start (GTK_BOX (search_hbox), search_button, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (search_button, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, search_button, _("Search for expression"), NULL);

  clear_button = gtk_button_new_with_mnemonic (_("Clear"));
  gtk_widget_set_name (clear_button, "clear_button");
  gtk_widget_show (clear_button);
  gtk_box_pack_start (GTK_BOX (search_hbox), clear_button, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, clear_button, _("Clear search expression"), NULL);

  pkg_vpaned = gtk_vpaned_new ();
  gtk_widget_set_name (pkg_vpaned, "pkg_vpaned");
  gtk_widget_show (pkg_vpaned);
  gtk_box_pack_start (GTK_BOX (gslapt_vbox), pkg_vpaned, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pkg_vpaned), 6);

  pkg_list_scrolled = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (pkg_list_scrolled, "pkg_list_scrolled");
  gtk_widget_show (pkg_list_scrolled);
  gtk_paned_pack1 (GTK_PANED (pkg_vpaned), pkg_list_scrolled, TRUE, FALSE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (pkg_list_scrolled), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  pkg_listing_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (pkg_listing_treeview, "pkg_listing_treeview");
  gtk_widget_show (pkg_listing_treeview);
  gtk_container_add (GTK_CONTAINER (pkg_list_scrolled), pkg_listing_treeview);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (pkg_listing_treeview), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (pkg_listing_treeview), TRUE);

  pkg_info_action_hbox = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (pkg_info_action_hbox, "pkg_info_action_hbox");
  gtk_widget_show (pkg_info_action_hbox);
  gtk_paned_pack2 (GTK_PANED (pkg_vpaned), pkg_info_action_hbox, TRUE, FALSE);
  gtk_container_set_border_width (GTK_CONTAINER (pkg_info_action_hbox), 6);

  pkg_info_notebook = gtk_notebook_new ();
  gtk_widget_set_name (pkg_info_notebook, "pkg_info_notebook");
  gtk_widget_show (pkg_info_notebook);
  gtk_box_pack_start (GTK_BOX (pkg_info_action_hbox), pkg_info_notebook, TRUE, TRUE, 0);
  gtk_notebook_set_show_border (GTK_NOTEBOOK (pkg_info_notebook), FALSE);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (pkg_info_notebook), TRUE);

  scrolledwindow20 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow20, "scrolledwindow20");
  gtk_widget_show (scrolledwindow20);
  gtk_container_add (GTK_CONTAINER (pkg_info_notebook), scrolledwindow20);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow20), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow20), GTK_SHADOW_IN);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport1, "viewport1");
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow20), viewport1);

  vbox63 = gtk_vbox_new (FALSE, 18);
  gtk_widget_set_name (vbox63, "vbox63");
  gtk_widget_show (vbox63);
  gtk_container_add (GTK_CONTAINER (viewport1), vbox63);
  gtk_container_set_border_width (GTK_CONTAINER (vbox63), 6);

  table2 = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table2, "table2");
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox63), table2, FALSE, FALSE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 12);

  label226 = gtk_label_new (_("<b>Name</b>"));
  gtk_widget_set_name (label226, "label226");
  gtk_widget_show (label226);
  gtk_table_attach (GTK_TABLE (table2), label226, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label226), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label226), 0, 0.5);

  label227 = gtk_label_new (_("<b>Description</b>"));
  gtk_widget_set_name (label227, "label227");
  gtk_widget_show (label227);
  gtk_table_attach (GTK_TABLE (table2), label227, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label227), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label227), 0, 0.5);

  label244 = gtk_label_new (_("<b>Location</b>"));
  gtk_widget_set_name (label244, "label244");
  gtk_widget_show (label244);
  gtk_table_attach (GTK_TABLE (table2), label244, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label244), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label244), 0, 0.5);

  pkg_info_name = gtk_label_new (_("No package is selected.\n"));
  gtk_widget_set_name (pkg_info_name, "pkg_info_name");
  gtk_widget_show (pkg_info_name);
  gtk_table_attach (GTK_TABLE (table2), pkg_info_name, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pkg_info_name, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (pkg_info_name), TRUE);
  gtk_label_set_selectable (GTK_LABEL (pkg_info_name), TRUE);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_name), 0, 0.5);

  pkg_info_description = gtk_label_new ("");
  gtk_widget_set_name (pkg_info_description, "pkg_info_description");
  gtk_widget_show (pkg_info_description);
  gtk_table_attach (GTK_TABLE (table2), pkg_info_description, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pkg_info_description, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (pkg_info_description), TRUE);
  gtk_label_set_selectable (GTK_LABEL (pkg_info_description), TRUE);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_description), 0, 0.5);

  pkg_info_location = gtk_label_new ("");
  gtk_widget_set_name (pkg_info_location, "pkg_info_location");
  gtk_widget_show (pkg_info_location);
  gtk_table_attach (GTK_TABLE (table2), pkg_info_location, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pkg_info_location, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (pkg_info_location), TRUE);
  gtk_label_set_selectable (GTK_LABEL (pkg_info_location), TRUE);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_location), 0, 0.5);

  table3 = gtk_table_new (4, 2, FALSE);
  gtk_widget_set_name (table3, "table3");
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox63), table3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table3), 1);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 12);

  label237 = gtk_label_new (_("<b>Version</b>"));
  gtk_widget_set_name (label237, "label237");
  gtk_widget_show (label237);
  gtk_table_attach (GTK_TABLE (table3), label237, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label237), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label237), 0, 0.5);

  label238 = gtk_label_new (_("<b>Size</b>"));
  gtk_widget_set_name (label238, "label238");
  gtk_widget_show (label238);
  gtk_table_attach (GTK_TABLE (table3), label238, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label238), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label238), 0, 0.5);

  label239 = gtk_label_new (_("<b>Installed Size</b>"));
  gtk_widget_set_name (label239, "label239");
  gtk_widget_show (label239);
  gtk_table_attach (GTK_TABLE (table3), label239, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label239), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label239), 0, 0.5);

  label245 = gtk_label_new (_("<b>Mirror</b>"));
  gtk_widget_set_name (label245, "label245");
  gtk_widget_show (label245);
  gtk_table_attach (GTK_TABLE (table3), label245, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label245), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label245), 0, 0.5);

  pkg_info_version = gtk_label_new ("");
  gtk_widget_set_name (pkg_info_version, "pkg_info_version");
  gtk_widget_show (pkg_info_version);
  gtk_table_attach (GTK_TABLE (table3), pkg_info_version, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pkg_info_version, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (pkg_info_version), TRUE);
  gtk_label_set_selectable (GTK_LABEL (pkg_info_version), TRUE);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_version), 0, 0.5);

  pkg_info_size = gtk_label_new ("");
  gtk_widget_set_name (pkg_info_size, "pkg_info_size");
  gtk_widget_show (pkg_info_size);
  gtk_table_attach (GTK_TABLE (table3), pkg_info_size, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pkg_info_size, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (pkg_info_size), TRUE);
  gtk_label_set_selectable (GTK_LABEL (pkg_info_size), TRUE);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_size), 0, 0.5);

  pkg_info_installed_size = gtk_label_new ("");
  gtk_widget_set_name (pkg_info_installed_size, "pkg_info_installed_size");
  gtk_widget_show (pkg_info_installed_size);
  gtk_table_attach (GTK_TABLE (table3), pkg_info_installed_size, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pkg_info_installed_size, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (pkg_info_installed_size), TRUE);
  gtk_label_set_selectable (GTK_LABEL (pkg_info_installed_size), TRUE);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_installed_size), 0, 0.5);

  pkg_info_mirror = gtk_label_new ("");
  gtk_widget_set_name (pkg_info_mirror, "pkg_info_mirror");
  gtk_widget_show (pkg_info_mirror);
  gtk_table_attach (GTK_TABLE (table3), pkg_info_mirror, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pkg_info_mirror, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (pkg_info_mirror), TRUE);
  gtk_label_set_selectable (GTK_LABEL (pkg_info_mirror), TRUE);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_mirror), 0, 0.5);

  pkg_info_common_label = gtk_label_new (_("Common"));
  gtk_widget_set_name (pkg_info_common_label, "pkg_info_common_label");
  gtk_widget_show (pkg_info_common_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (pkg_info_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (pkg_info_notebook), 0), pkg_info_common_label);

  vbox64 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox64, "vbox64");
  gtk_widget_show (vbox64);
  gtk_container_add (GTK_CONTAINER (pkg_info_notebook), vbox64);
  gtk_container_set_border_width (GTK_CONTAINER (vbox64), 12);

  scrolledwindow19 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow19, "scrolledwindow19");
  gtk_widget_show (scrolledwindow19);
  gtk_box_pack_start (GTK_BOX (vbox64), scrolledwindow19, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow19), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow19), GTK_SHADOW_IN);

  pkg_description_textview = gtk_text_view_new ();
  gtk_widget_set_name (pkg_description_textview, "pkg_description_textview");
  gtk_widget_show (pkg_description_textview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow19), pkg_description_textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (pkg_description_textview), FALSE);

  pkg_info_description_label = gtk_label_new (_("Description"));
  gtk_widget_set_name (pkg_info_description_label, "pkg_info_description_label");
  gtk_widget_show (pkg_info_description_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (pkg_info_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (pkg_info_notebook), 1), pkg_info_description_label);

  scrolledwindow21 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow21, "scrolledwindow21");
  gtk_widget_show (scrolledwindow21);
  gtk_container_add (GTK_CONTAINER (pkg_info_notebook), scrolledwindow21);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow21), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow21), GTK_SHADOW_IN);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport2, "viewport2");
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow21), viewport2);

  pkg_info_dep_vbox = gtk_vbox_new (FALSE, 18);
  gtk_widget_set_name (pkg_info_dep_vbox, "pkg_info_dep_vbox");
  gtk_widget_show (pkg_info_dep_vbox);
  gtk_container_add (GTK_CONTAINER (viewport2), pkg_info_dep_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (pkg_info_dep_vbox), 6);

  table4 = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table4, "table4");
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (pkg_info_dep_vbox), table4, FALSE, FALSE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 12);

  label247 = gtk_label_new (_("<b>Required</b>"));
  gtk_widget_set_name (label247, "label247");
  gtk_widget_show (label247);
  gtk_table_attach (GTK_TABLE (table4), label247, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label247), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label247), 0, 0.5);

  label248 = gtk_label_new (_("<b>Conflicts</b>"));
  gtk_widget_set_name (label248, "label248");
  gtk_widget_show (label248);
  gtk_table_attach (GTK_TABLE (table4), label248, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label248), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label248), 0, 0.5);

  label249 = gtk_label_new (_("<b>Suggests</b>"));
  gtk_widget_set_name (label249, "label249");
  gtk_widget_show (label249);
  gtk_table_attach (GTK_TABLE (table4), label249, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label249), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label249), 0, 0.5);

  pkg_info_required = gtk_label_new ("");
  gtk_widget_set_name (pkg_info_required, "pkg_info_required");
  gtk_widget_show (pkg_info_required);
  gtk_table_attach (GTK_TABLE (table4), pkg_info_required, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pkg_info_required, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (pkg_info_required), TRUE);
  gtk_label_set_selectable (GTK_LABEL (pkg_info_required), TRUE);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_required), 0, 0.5);

  pkg_info_conflicts = gtk_label_new ("");
  gtk_widget_set_name (pkg_info_conflicts, "pkg_info_conflicts");
  gtk_widget_show (pkg_info_conflicts);
  gtk_table_attach (GTK_TABLE (table4), pkg_info_conflicts, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pkg_info_conflicts, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (pkg_info_conflicts), TRUE);
  gtk_label_set_selectable (GTK_LABEL (pkg_info_conflicts), TRUE);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_conflicts), 0, 0.5);

  pkg_info_suggests = gtk_label_new ("");
  gtk_widget_set_name (pkg_info_suggests, "pkg_info_suggests");
  gtk_widget_show (pkg_info_suggests);
  gtk_table_attach (GTK_TABLE (table4), pkg_info_suggests, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (pkg_info_suggests, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (pkg_info_suggests), TRUE);
  gtk_label_set_selectable (GTK_LABEL (pkg_info_suggests), TRUE);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_suggests), 0, 0.5);

  pkg_info_dependencies_label = gtk_label_new (_("Dependencies"));
  gtk_widget_set_name (pkg_info_dependencies_label, "pkg_info_dependencies_label");
  gtk_widget_show (pkg_info_dependencies_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (pkg_info_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (pkg_info_notebook), 2), pkg_info_dependencies_label);

  pkg_action_vbox = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (pkg_action_vbox, "pkg_action_vbox");
  gtk_widget_show (pkg_action_vbox);
  gtk_box_pack_start (GTK_BOX (pkg_info_action_hbox), pkg_action_vbox, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (pkg_action_vbox), 6);

  label246 = gtk_label_new ("");
  gtk_widget_set_name (label246, "label246");
  gtk_widget_show (label246);
  gtk_box_pack_start (GTK_BOX (pkg_action_vbox), label246, FALSE, FALSE, 0);

  pkg_info_action_install_upgrade_button = gtk_button_new ();
  gtk_widget_set_name (pkg_info_action_install_upgrade_button, "pkg_info_action_install_upgrade_button");
  gtk_widget_show (pkg_info_action_install_upgrade_button);
  gtk_box_pack_start (GTK_BOX (pkg_action_vbox), pkg_info_action_install_upgrade_button, FALSE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, pkg_info_action_install_upgrade_button, _("Install/Upgrade package"), NULL);
  gtk_widget_add_accelerator (pkg_info_action_install_upgrade_button, "clicked", accel_group,
                              GDK_i, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (pkg_info_action_install_upgrade_button, "clicked", accel_group,
                              GDK_u, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment27, "alignment27");
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (pkg_info_action_install_upgrade_button), alignment27);

  hbox78 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox78, "hbox78");
  gtk_widget_show (hbox78);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox78);

  image746 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image746, "image746");
  gtk_widget_show (image746);
  gtk_box_pack_start (GTK_BOX (hbox78), image746, FALSE, FALSE, 0);

  label131 = gtk_label_new_with_mnemonic (_("Install"));
  gtk_widget_set_name (label131, "label131");
  gtk_widget_show (label131);
  gtk_box_pack_start (GTK_BOX (hbox78), label131, FALSE, FALSE, 0);

  pkg_info_action_remove_button = gtk_button_new ();
  gtk_widget_set_name (pkg_info_action_remove_button, "pkg_info_action_remove_button");
  gtk_widget_show (pkg_info_action_remove_button);
  gtk_box_pack_start (GTK_BOX (pkg_action_vbox), pkg_info_action_remove_button, FALSE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, pkg_info_action_remove_button, _("Remove package"), NULL);
  gtk_widget_add_accelerator (pkg_info_action_remove_button, "clicked", accel_group,
                              GDK_r, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment28, "alignment28");
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (pkg_info_action_remove_button), alignment28);

  hbox79 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox79, "hbox79");
  gtk_widget_show (hbox79);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox79);

  image747 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image747, "image747");
  gtk_widget_show (image747);
  gtk_box_pack_start (GTK_BOX (hbox79), image747, FALSE, FALSE, 0);

  label132 = gtk_label_new_with_mnemonic (_("Remove"));
  gtk_widget_set_name (label132, "label132");
  gtk_widget_show (label132);
  gtk_box_pack_start (GTK_BOX (hbox79), label132, FALSE, FALSE, 0);

  bottom_statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (bottom_statusbar, "bottom_statusbar");
  gtk_widget_show (bottom_statusbar);
  gtk_box_pack_start (GTK_BOX (gslapt_vbox), bottom_statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) gslapt, "destroy",
                    G_CALLBACK (on_gslapt_destroy),
                    NULL);
  g_signal_connect ((gpointer) quit, "activate",
                    G_CALLBACK (on_gslapt_destroy),
                    NULL);
  g_signal_connect ((gpointer) preferences2, "activate",
                    G_CALLBACK (open_preferences),
                    NULL);
  g_signal_connect ((gpointer) about3, "activate",
                    G_CALLBACK (open_about),
                    NULL);
  g_signal_connect_swapped ((gpointer) action_bar_update_button, "clicked",
                            G_CALLBACK (update_callback),
                            GTK_OBJECT (gslapt));
  g_signal_connect_swapped ((gpointer) action_bar_upgrade_button, "clicked",
                            G_CALLBACK (upgrade_callback),
                            GTK_OBJECT (gslapt));
  g_signal_connect ((gpointer) action_bar_clean_button, "clicked",
                    G_CALLBACK (clean_callback),
                    NULL);
  g_signal_connect_swapped ((gpointer) action_bar_execute_button, "clicked",
                            G_CALLBACK (execute_callback),
                            GTK_OBJECT (gslapt));
  g_signal_connect_swapped ((gpointer) search_entry, "editing_done",
                            G_CALLBACK (search_button_clicked),
                            GTK_OBJECT (gslapt));
  g_signal_connect_swapped ((gpointer) search_entry, "activate",
                            G_CALLBACK (search_button_clicked),
                            GTK_OBJECT (gslapt));
  g_signal_connect_swapped ((gpointer) search_button, "clicked",
                            G_CALLBACK (search_button_clicked),
                            GTK_OBJECT (gslapt));
  g_signal_connect_swapped ((gpointer) clear_button, "clicked",
                            G_CALLBACK (clear_button_clicked),
                            GTK_OBJECT (search_entry));
  g_signal_connect_swapped ((gpointer) pkg_info_action_install_upgrade_button, "clicked",
                            G_CALLBACK (add_pkg_for_install),
                            GTK_OBJECT (gslapt));
  g_signal_connect_swapped ((gpointer) pkg_info_action_remove_button, "clicked",
                            G_CALLBACK (add_pkg_for_removal),
                            GTK_OBJECT (gslapt));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gslapt, gslapt, "gslapt");
  GLADE_HOOKUP_OBJECT (gslapt, gslapt_vbox, "gslapt_vbox");
  GLADE_HOOKUP_OBJECT (gslapt, top_menubar, "top_menubar");
  GLADE_HOOKUP_OBJECT (gslapt, actions2, "actions2");
  GLADE_HOOKUP_OBJECT (gslapt, actions2_menu, "actions2_menu");
  GLADE_HOOKUP_OBJECT (gslapt, quit, "quit");
  GLADE_HOOKUP_OBJECT (gslapt, settings1, "settings1");
  GLADE_HOOKUP_OBJECT (gslapt, settings1_menu, "settings1_menu");
  GLADE_HOOKUP_OBJECT (gslapt, preferences2, "preferences2");
  GLADE_HOOKUP_OBJECT (gslapt, image863, "image863");
  GLADE_HOOKUP_OBJECT (gslapt, help3, "help3");
  GLADE_HOOKUP_OBJECT (gslapt, help3_menu, "help3_menu");
  GLADE_HOOKUP_OBJECT (gslapt, about3, "about3");
  GLADE_HOOKUP_OBJECT (gslapt, image864, "image864");
  GLADE_HOOKUP_OBJECT (gslapt, action_toolbar, "action_toolbar");
  GLADE_HOOKUP_OBJECT (gslapt, action_bar_update_button, "action_bar_update_button");
  GLADE_HOOKUP_OBJECT (gslapt, action_bar_upgrade_button, "action_bar_upgrade_button");
  GLADE_HOOKUP_OBJECT (gslapt, action_bar_clean_button, "action_bar_clean_button");
  GLADE_HOOKUP_OBJECT (gslapt, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (gslapt, action_bar_execute_button, "action_bar_execute_button");
  GLADE_HOOKUP_OBJECT (gslapt, search_vbox, "search_vbox");
  GLADE_HOOKUP_OBJECT (gslapt, search_align, "search_align");
  GLADE_HOOKUP_OBJECT (gslapt, search_hbox, "search_hbox");
  GLADE_HOOKUP_OBJECT (gslapt, search_entry, "search_entry");
  GLADE_HOOKUP_OBJECT (gslapt, search_button, "search_button");
  GLADE_HOOKUP_OBJECT (gslapt, clear_button, "clear_button");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_vpaned, "pkg_vpaned");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_list_scrolled, "pkg_list_scrolled");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_listing_treeview, "pkg_listing_treeview");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_hbox, "pkg_info_action_hbox");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_notebook, "pkg_info_notebook");
  GLADE_HOOKUP_OBJECT (gslapt, scrolledwindow20, "scrolledwindow20");
  GLADE_HOOKUP_OBJECT (gslapt, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (gslapt, vbox63, "vbox63");
  GLADE_HOOKUP_OBJECT (gslapt, table2, "table2");
  GLADE_HOOKUP_OBJECT (gslapt, label226, "label226");
  GLADE_HOOKUP_OBJECT (gslapt, label227, "label227");
  GLADE_HOOKUP_OBJECT (gslapt, label244, "label244");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_name, "pkg_info_name");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_description, "pkg_info_description");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_location, "pkg_info_location");
  GLADE_HOOKUP_OBJECT (gslapt, table3, "table3");
  GLADE_HOOKUP_OBJECT (gslapt, label237, "label237");
  GLADE_HOOKUP_OBJECT (gslapt, label238, "label238");
  GLADE_HOOKUP_OBJECT (gslapt, label239, "label239");
  GLADE_HOOKUP_OBJECT (gslapt, label245, "label245");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_version, "pkg_info_version");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_size, "pkg_info_size");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_installed_size, "pkg_info_installed_size");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_mirror, "pkg_info_mirror");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_common_label, "pkg_info_common_label");
  GLADE_HOOKUP_OBJECT (gslapt, vbox64, "vbox64");
  GLADE_HOOKUP_OBJECT (gslapt, scrolledwindow19, "scrolledwindow19");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_description_textview, "pkg_description_textview");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_description_label, "pkg_info_description_label");
  GLADE_HOOKUP_OBJECT (gslapt, scrolledwindow21, "scrolledwindow21");
  GLADE_HOOKUP_OBJECT (gslapt, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_dep_vbox, "pkg_info_dep_vbox");
  GLADE_HOOKUP_OBJECT (gslapt, table4, "table4");
  GLADE_HOOKUP_OBJECT (gslapt, label247, "label247");
  GLADE_HOOKUP_OBJECT (gslapt, label248, "label248");
  GLADE_HOOKUP_OBJECT (gslapt, label249, "label249");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_required, "pkg_info_required");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_conflicts, "pkg_info_conflicts");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_suggests, "pkg_info_suggests");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_dependencies_label, "pkg_info_dependencies_label");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_action_vbox, "pkg_action_vbox");
  GLADE_HOOKUP_OBJECT (gslapt, label246, "label246");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_install_upgrade_button, "pkg_info_action_install_upgrade_button");
  GLADE_HOOKUP_OBJECT (gslapt, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (gslapt, hbox78, "hbox78");
  GLADE_HOOKUP_OBJECT (gslapt, image746, "image746");
  GLADE_HOOKUP_OBJECT (gslapt, label131, "label131");
  GLADE_HOOKUP_OBJECT (gslapt, pkg_info_action_remove_button, "pkg_info_action_remove_button");
  GLADE_HOOKUP_OBJECT (gslapt, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (gslapt, hbox79, "hbox79");
  GLADE_HOOKUP_OBJECT (gslapt, image747, "image747");
  GLADE_HOOKUP_OBJECT (gslapt, label132, "label132");
  GLADE_HOOKUP_OBJECT (gslapt, bottom_statusbar, "bottom_statusbar");
  GLADE_HOOKUP_OBJECT_NO_REF (gslapt, tooltips, "tooltips");

  gtk_widget_grab_default (search_entry);
  gtk_window_add_accel_group (GTK_WINDOW (gslapt), accel_group);

  return gslapt;
}

GtkWidget*
create_transaction_window (void)
{
  GtkWidget *transaction_window;
  GdkPixbuf *transaction_window_icon_pixbuf;
  GtkWidget *vbox47;
  GtkWidget *vbox61;
  GtkWidget *hbox97;
  GtkWidget *image852;
  GtkWidget *vbox62;
  GtkWidget *label167;
  GtkWidget *label168;
  GtkWidget *scrolledwindow18;
  GtkWidget *transaction_summary_treeview;
  GtkWidget *summary_breakdown;
  GtkWidget *summary_pkg_numbers;
  GtkWidget *summary_dl_size;
  GtkWidget *summary_free_space;
  GtkWidget *download_only_checkbutton;
  GtkWidget *hbuttonbox1;
  GtkWidget *button2;
  GtkWidget *button3;

  transaction_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (transaction_window, "transaction_window");
  gtk_container_set_border_width (GTK_CONTAINER (transaction_window), 12);
  gtk_window_set_title (GTK_WINDOW (transaction_window), _("Summary"));
  gtk_window_set_position (GTK_WINDOW (transaction_window), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (transaction_window), 200, 400);
  transaction_window_icon_pixbuf = create_pixbuf ("gslapt.png");
  if (transaction_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (transaction_window), transaction_window_icon_pixbuf);
      gdk_pixbuf_unref (transaction_window_icon_pixbuf);
    }
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (transaction_window), TRUE);
  gtk_window_set_gravity (GTK_WINDOW (transaction_window), GDK_GRAVITY_CENTER);

  vbox47 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox47, "vbox47");
  gtk_widget_show (vbox47);
  gtk_container_add (GTK_CONTAINER (transaction_window), vbox47);

  vbox61 = gtk_vbox_new (FALSE, 2);
  gtk_widget_set_name (vbox61, "vbox61");
  gtk_widget_show (vbox61);
  gtk_box_pack_start (GTK_BOX (vbox47), vbox61, TRUE, TRUE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox61), 6);

  hbox97 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox97, "hbox97");
  gtk_widget_show (hbox97);
  gtk_box_pack_start (GTK_BOX (vbox61), hbox97, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox97), 6);

  image852 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_set_name (image852, "image852");
  gtk_widget_show (image852);
  gtk_box_pack_start (GTK_BOX (hbox97), image852, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (image852), 0, 0);

  vbox62 = gtk_vbox_new (FALSE, 2);
  gtk_widget_set_name (vbox62, "vbox62");
  gtk_widget_show (vbox62);
  gtk_box_pack_start (GTK_BOX (hbox97), vbox62, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox62), 6);

  label167 = gtk_label_new (_("<span weight=\"bold\" size=\"large\">Apply the folowing changes?</span>"));
  gtk_widget_set_name (label167, "label167");
  gtk_widget_show (label167);
  gtk_box_pack_start (GTK_BOX (vbox62), label167, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label167), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label167), 0, 0);

  label168 = gtk_label_new (_("This is a summary of the changes about to be performed."));
  gtk_widget_set_name (label168, "label168");
  gtk_widget_show (label168);
  gtk_box_pack_start (GTK_BOX (vbox62), label168, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label168), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label168), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label168), 0, 6);

  scrolledwindow18 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow18, "scrolledwindow18");
  gtk_widget_show (scrolledwindow18);
  gtk_box_pack_start (GTK_BOX (vbox61), scrolledwindow18, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow18), 1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow18), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  transaction_summary_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (transaction_summary_treeview, "transaction_summary_treeview");
  gtk_widget_show (transaction_summary_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow18), transaction_summary_treeview);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (transaction_summary_treeview), FALSE);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (transaction_summary_treeview), TRUE);

  summary_breakdown = gtk_vbox_new (FALSE, 2);
  gtk_widget_set_name (summary_breakdown, "summary_breakdown");
  gtk_widget_show (summary_breakdown);
  gtk_box_pack_start (GTK_BOX (vbox61), summary_breakdown, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (summary_breakdown), 6);

  summary_pkg_numbers = gtk_label_new ("");
  gtk_widget_set_name (summary_pkg_numbers, "summary_pkg_numbers");
  gtk_widget_show (summary_pkg_numbers);
  gtk_box_pack_start (GTK_BOX (summary_breakdown), summary_pkg_numbers, FALSE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (summary_pkg_numbers), TRUE);
  gtk_misc_set_alignment (GTK_MISC (summary_pkg_numbers), 0, 0);
  gtk_misc_set_padding (GTK_MISC (summary_pkg_numbers), 6, 1);

  summary_dl_size = gtk_label_new ("");
  gtk_widget_set_name (summary_dl_size, "summary_dl_size");
  gtk_widget_show (summary_dl_size);
  gtk_box_pack_start (GTK_BOX (summary_breakdown), summary_dl_size, FALSE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (summary_dl_size), TRUE);
  gtk_misc_set_alignment (GTK_MISC (summary_dl_size), 0, 0);
  gtk_misc_set_padding (GTK_MISC (summary_dl_size), 6, 1);

  summary_free_space = gtk_label_new ("");
  gtk_widget_set_name (summary_free_space, "summary_free_space");
  gtk_widget_show (summary_free_space);
  gtk_box_pack_start (GTK_BOX (summary_breakdown), summary_free_space, FALSE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (summary_free_space), TRUE);
  gtk_misc_set_alignment (GTK_MISC (summary_free_space), 0, 0);
  gtk_misc_set_padding (GTK_MISC (summary_free_space), 6, 1);

  download_only_checkbutton = gtk_check_button_new_with_mnemonic (_("Download packages only"));
  gtk_widget_set_name (download_only_checkbutton, "download_only_checkbutton");
  gtk_widget_show (download_only_checkbutton);
  gtk_box_pack_start (GTK_BOX (vbox61), download_only_checkbutton, FALSE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox47), hbuttonbox1, FALSE, TRUE, 1);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox1), 2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 6);

  button2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (button2, "button2");
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  button3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (button3, "button3");
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) transaction_window, "destroy_event",
                    G_CALLBACK (gtk_widget_destroy),
                    NULL);
  g_signal_connect_swapped ((gpointer) button2, "clicked",
                            G_CALLBACK (cancel_transaction),
                            GTK_OBJECT (transaction_window));
  g_signal_connect_swapped ((gpointer) button3, "clicked",
                            G_CALLBACK (on_transaction_okbutton1_clicked),
                            GTK_OBJECT (transaction_window));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (transaction_window, transaction_window, "transaction_window");
  GLADE_HOOKUP_OBJECT (transaction_window, vbox47, "vbox47");
  GLADE_HOOKUP_OBJECT (transaction_window, vbox61, "vbox61");
  GLADE_HOOKUP_OBJECT (transaction_window, hbox97, "hbox97");
  GLADE_HOOKUP_OBJECT (transaction_window, image852, "image852");
  GLADE_HOOKUP_OBJECT (transaction_window, vbox62, "vbox62");
  GLADE_HOOKUP_OBJECT (transaction_window, label167, "label167");
  GLADE_HOOKUP_OBJECT (transaction_window, label168, "label168");
  GLADE_HOOKUP_OBJECT (transaction_window, scrolledwindow18, "scrolledwindow18");
  GLADE_HOOKUP_OBJECT (transaction_window, transaction_summary_treeview, "transaction_summary_treeview");
  GLADE_HOOKUP_OBJECT (transaction_window, summary_breakdown, "summary_breakdown");
  GLADE_HOOKUP_OBJECT (transaction_window, summary_pkg_numbers, "summary_pkg_numbers");
  GLADE_HOOKUP_OBJECT (transaction_window, summary_dl_size, "summary_dl_size");
  GLADE_HOOKUP_OBJECT (transaction_window, summary_free_space, "summary_free_space");
  GLADE_HOOKUP_OBJECT (transaction_window, download_only_checkbutton, "download_only_checkbutton");
  GLADE_HOOKUP_OBJECT (transaction_window, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (transaction_window, button2, "button2");
  GLADE_HOOKUP_OBJECT (transaction_window, button3, "button3");

  return transaction_window;
}

GtkWidget*
create_progress_window (void)
{
  GtkWidget *progress_window;
  GdkPixbuf *progress_window_icon_pixbuf;
  GtkWidget *vbox49;
  GtkWidget *progress_progressbar;
  GtkWidget *dl_progress;
  GtkWidget *progress_action;
  GtkWidget *progress_message;
  GtkWidget *progress_package_description;

  progress_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (progress_window, "progress_window");
  gtk_container_set_border_width (GTK_CONTAINER (progress_window), 12);
  gtk_window_set_title (GTK_WINDOW (progress_window), _("working"));
  gtk_window_set_position (GTK_WINDOW (progress_window), GTK_WIN_POS_CENTER);
  progress_window_icon_pixbuf = create_pixbuf ("gslapt.png");
  if (progress_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (progress_window), progress_window_icon_pixbuf);
      gdk_pixbuf_unref (progress_window_icon_pixbuf);
    }
  gtk_window_set_gravity (GTK_WINDOW (progress_window), GDK_GRAVITY_CENTER);

  vbox49 = gtk_vbox_new (FALSE, 2);
  gtk_widget_set_name (vbox49, "vbox49");
  gtk_widget_show (vbox49);
  gtk_container_add (GTK_CONTAINER (progress_window), vbox49);
  gtk_container_set_border_width (GTK_CONTAINER (vbox49), 6);

  progress_progressbar = gtk_progress_bar_new ();
  gtk_widget_set_name (progress_progressbar, "progress_progressbar");
  gtk_widget_show (progress_progressbar);
  gtk_box_pack_start (GTK_BOX (vbox49), progress_progressbar, FALSE, TRUE, 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (progress_progressbar), _("total progress"));

  dl_progress = gtk_progress_bar_new ();
  gtk_widget_set_name (dl_progress, "dl_progress");
  gtk_widget_show (dl_progress);
  gtk_box_pack_start (GTK_BOX (vbox49), dl_progress, FALSE, TRUE, 2);

  progress_action = gtk_label_new ("");
  gtk_widget_set_name (progress_action, "progress_action");
  gtk_widget_show (progress_action);
  gtk_box_pack_start (GTK_BOX (vbox49), progress_action, TRUE, TRUE, 6);

  progress_message = gtk_label_new ("");
  gtk_widget_set_name (progress_message, "progress_message");
  gtk_widget_show (progress_message);
  gtk_box_pack_start (GTK_BOX (vbox49), progress_message, TRUE, TRUE, 6);

  progress_package_description = gtk_label_new ("");
  gtk_widget_set_name (progress_package_description, "progress_package_description");
  gtk_widget_show (progress_package_description);
  gtk_box_pack_start (GTK_BOX (vbox49), progress_package_description, TRUE, TRUE, 6);
  gtk_misc_set_alignment (GTK_MISC (progress_package_description), 0, 0);

  g_signal_connect ((gpointer) progress_window, "delete_event",
                    G_CALLBACK (gtk_true),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (progress_window, progress_window, "progress_window");
  GLADE_HOOKUP_OBJECT (progress_window, vbox49, "vbox49");
  GLADE_HOOKUP_OBJECT (progress_window, progress_progressbar, "progress_progressbar");
  GLADE_HOOKUP_OBJECT (progress_window, dl_progress, "dl_progress");
  GLADE_HOOKUP_OBJECT (progress_window, progress_action, "progress_action");
  GLADE_HOOKUP_OBJECT (progress_window, progress_message, "progress_message");
  GLADE_HOOKUP_OBJECT (progress_window, progress_package_description, "progress_package_description");

  return progress_window;
}

GtkWidget*
create_about (void)
{
  GtkWidget *about;
  GdkPixbuf *about_icon_pixbuf;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox50;
  GtkWidget *image853;
  GtkWidget *label146;
  GtkWidget *label147;
  GtkWidget *label170;
  GtkWidget *label149;
  GtkWidget *dialog_action_area1;
  GtkWidget *closebutton1;

  about = gtk_dialog_new ();
  gtk_widget_set_name (about, "about");
  gtk_window_set_title (GTK_WINDOW (about), _("About gslapt"));
  gtk_window_set_position (GTK_WINDOW (about), GTK_WIN_POS_CENTER);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (about), TRUE);
  about_icon_pixbuf = create_pixbuf ("gslapt.png");
  if (about_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (about), about_icon_pixbuf);
      gdk_pixbuf_unref (about_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (about), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_window_set_gravity (GTK_WINDOW (about), GDK_GRAVITY_CENTER);

  dialog_vbox1 = GTK_DIALOG (about)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_widget_show (dialog_vbox1);

  vbox50 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox50, "vbox50");
  gtk_widget_show (vbox50);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox50, TRUE, TRUE, 0);

  image853 = create_pixmap (about, "gslapt.png");
  gtk_widget_set_name (image853, "image853");
  gtk_widget_show (image853);
  gtk_box_pack_start (GTK_BOX (vbox50), image853, TRUE, TRUE, 0);

  label146 = gtk_label_new ("<span weight=\"bold\" size=\"xx-large\"></span>");
  gtk_widget_set_name (label146, "label146");
  gtk_widget_show (label146);
  gtk_box_pack_start (GTK_BOX (vbox50), label146, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (label146, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label146), TRUE);
  gtk_label_set_justify (GTK_LABEL (label146), GTK_JUSTIFY_RIGHT);
  gtk_label_set_selectable (GTK_LABEL (label146), TRUE);

  label147 = gtk_label_new (_("gslapt is a GTK+ frontend to slapt-get, an APT like package system for Slackware"));
  gtk_widget_set_name (label147, "label147");
  gtk_widget_show (label147);
  gtk_box_pack_start (GTK_BOX (vbox50), label147, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (label147, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (label147), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label147), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label147), TRUE);

  label170 = gtk_label_new ("");
  gtk_widget_set_name (label170, "label170");
  gtk_widget_show (label170);
  gtk_box_pack_start (GTK_BOX (vbox50), label170, FALSE, FALSE, 0);

  label149 = gtk_label_new ("<span size=\"small\">Copyright (c) 2005 Jason Woodward\nhttp://software.jaos.org/#gslapt</span>");
  gtk_widget_set_name (label149, "label149");
  gtk_widget_show (label149);
  gtk_box_pack_start (GTK_BOX (vbox50), label149, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (label149, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label149), TRUE);
  gtk_label_set_justify (GTK_LABEL (label149), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label149), TRUE);

  dialog_action_area1 = GTK_DIALOG (about)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (closebutton1, "closebutton1");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (about), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) closebutton1, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (about));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about, about, "about");
  GLADE_HOOKUP_OBJECT_NO_REF (about, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (about, vbox50, "vbox50");
  GLADE_HOOKUP_OBJECT (about, image853, "image853");
  GLADE_HOOKUP_OBJECT (about, label146, "label146");
  GLADE_HOOKUP_OBJECT (about, label147, "label147");
  GLADE_HOOKUP_OBJECT (about, label170, "label170");
  GLADE_HOOKUP_OBJECT (about, label149, "label149");
  GLADE_HOOKUP_OBJECT_NO_REF (about, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (about, closebutton1, "closebutton1");

  return about;
}

GtkWidget*
create_notification (void)
{
  GtkWidget *notification;
  GdkPixbuf *notification_icon_pixbuf;
  GtkWidget *dialog_vbox3;
  GtkWidget *notification_label;
  GtkWidget *dialog_action_area3;
  GtkWidget *okbutton2;

  notification = gtk_dialog_new ();
  gtk_widget_set_name (notification, "notification");
  gtk_container_set_border_width (GTK_CONTAINER (notification), 2);
  gtk_window_set_position (GTK_WINDOW (notification), GTK_WIN_POS_CENTER);
  notification_icon_pixbuf = create_pixbuf ("gslapt.png");
  if (notification_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (notification), notification_icon_pixbuf);
      gdk_pixbuf_unref (notification_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (notification), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_window_set_gravity (GTK_WINDOW (notification), GDK_GRAVITY_CENTER);

  dialog_vbox3 = GTK_DIALOG (notification)->vbox;
  gtk_widget_set_name (dialog_vbox3, "dialog_vbox3");
  gtk_widget_show (dialog_vbox3);

  notification_label = gtk_label_new ("");
  gtk_widget_set_name (notification_label, "notification_label");
  gtk_widget_show (notification_label);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), notification_label, TRUE, TRUE, 2);
  gtk_label_set_use_markup (GTK_LABEL (notification_label), TRUE);

  dialog_action_area3 = GTK_DIALOG (notification)->action_area;
  gtk_widget_set_name (dialog_action_area3, "dialog_action_area3");
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (okbutton2, "okbutton2");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (notification), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) okbutton2, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (notification));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (notification, notification, "notification");
  GLADE_HOOKUP_OBJECT_NO_REF (notification, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (notification, notification_label, "notification_label");
  GLADE_HOOKUP_OBJECT_NO_REF (notification, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (notification, okbutton2, "okbutton2");

  return notification;
}

GtkWidget*
create_trash (void)
{
  GtkWidget *trash;
  GtkWidget *frame1;
  GtkWidget *alignment30;
  GtkWidget *pkg_info_frame;
  GtkWidget *pkg_info_action_table;
  GtkWidget *pkg_info_action_name_label;
  GtkWidget *pkg_info_action_name_entry;
  GtkWidget *pkg_info_action_description_label;
  GtkWidget *pkg_info_action_description_entry;
  GtkWidget *pkg_info_action_version_label;
  GtkWidget *pkg_info_action_version_entry;
  GtkWidget *pkg_info_action_size_label;
  GtkWidget *pkg_info_action_size_entry;
  GtkWidget *pkg_info_action_isize_label;
  GtkWidget *pkg_info_action_isize_entry;
  GtkWidget *pkg_info_action_required_label;
  GtkWidget *pkg_info_action_required_entry;
  GtkWidget *pkg_info_action_conflicts_label;
  GtkWidget *pkg_info_action_conflicts_entry;
  GtkWidget *pkg_info_action_suggests_label;
  GtkWidget *pkg_info_action_suggests_entry;
  GtkWidget *pkg_info_action_mirror_label;
  GtkWidget *pkg_info_action_mirror_entry;
  GtkWidget *pkg_info_label;
  GtkWidget *label171;

  trash = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (trash, "trash");
  gtk_window_set_title (GTK_WINDOW (trash), _("window1"));

  frame1 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_show (frame1);
  gtk_container_add (GTK_CONTAINER (trash), frame1);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_NONE);

  alignment30 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment30, "alignment30");
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (frame1), alignment30);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment30), 0, 0, 12, 0);

  pkg_info_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (pkg_info_frame, "pkg_info_frame");
  gtk_widget_show (pkg_info_frame);
  gtk_container_add (GTK_CONTAINER (alignment30), pkg_info_frame);
  gtk_frame_set_shadow_type (GTK_FRAME (pkg_info_frame), GTK_SHADOW_NONE);

  pkg_info_action_table = gtk_table_new (9, 2, FALSE);
  gtk_widget_set_name (pkg_info_action_table, "pkg_info_action_table");
  gtk_widget_show (pkg_info_action_table);
  gtk_container_add (GTK_CONTAINER (pkg_info_frame), pkg_info_action_table);
  gtk_container_set_border_width (GTK_CONTAINER (pkg_info_action_table), 1);
  gtk_table_set_row_spacings (GTK_TABLE (pkg_info_action_table), 2);
  gtk_table_set_col_spacings (GTK_TABLE (pkg_info_action_table), 2);

  pkg_info_action_name_label = gtk_label_new (_("Name"));
  gtk_widget_set_name (pkg_info_action_name_label, "pkg_info_action_name_label");
  gtk_widget_show (pkg_info_action_name_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_name_label, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_name_label), 0, 0.5);

  pkg_info_action_name_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_name_entry, "pkg_info_action_name_entry");
  gtk_widget_show (pkg_info_action_name_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_name_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_name_entry), FALSE);

  pkg_info_action_description_label = gtk_label_new (_("Description"));
  gtk_widget_set_name (pkg_info_action_description_label, "pkg_info_action_description_label");
  gtk_widget_show (pkg_info_action_description_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_description_label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_description_label), 0, 0.5);

  pkg_info_action_description_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_description_entry, "pkg_info_action_description_entry");
  gtk_widget_show (pkg_info_action_description_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_description_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_description_entry), FALSE);

  pkg_info_action_version_label = gtk_label_new (_("Version"));
  gtk_widget_set_name (pkg_info_action_version_label, "pkg_info_action_version_label");
  gtk_widget_show (pkg_info_action_version_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_version_label, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_version_label), 0, 0.5);

  pkg_info_action_version_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_version_entry, "pkg_info_action_version_entry");
  gtk_widget_show (pkg_info_action_version_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_version_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_version_entry), FALSE);

  pkg_info_action_size_label = gtk_label_new (_("Size"));
  gtk_widget_set_name (pkg_info_action_size_label, "pkg_info_action_size_label");
  gtk_widget_show (pkg_info_action_size_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_size_label, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_size_label), 0, 0.5);

  pkg_info_action_size_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_size_entry, "pkg_info_action_size_entry");
  gtk_widget_show (pkg_info_action_size_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_size_entry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_size_entry), FALSE);

  pkg_info_action_isize_label = gtk_label_new (_("Installed Size"));
  gtk_widget_set_name (pkg_info_action_isize_label, "pkg_info_action_isize_label");
  gtk_widget_show (pkg_info_action_isize_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_isize_label, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_isize_label), 0, 0.5);

  pkg_info_action_isize_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_isize_entry, "pkg_info_action_isize_entry");
  gtk_widget_show (pkg_info_action_isize_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_isize_entry, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_isize_entry), FALSE);

  pkg_info_action_required_label = gtk_label_new (_("Required"));
  gtk_widget_set_name (pkg_info_action_required_label, "pkg_info_action_required_label");
  gtk_widget_show (pkg_info_action_required_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_required_label, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_required_label), 0, 0.5);

  pkg_info_action_required_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_required_entry, "pkg_info_action_required_entry");
  gtk_widget_show (pkg_info_action_required_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_required_entry, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_required_entry), FALSE);

  pkg_info_action_conflicts_label = gtk_label_new (_("Conflicts"));
  gtk_widget_set_name (pkg_info_action_conflicts_label, "pkg_info_action_conflicts_label");
  gtk_widget_show (pkg_info_action_conflicts_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_conflicts_label, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_conflicts_label), 0, 0.5);

  pkg_info_action_conflicts_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_conflicts_entry, "pkg_info_action_conflicts_entry");
  gtk_widget_show (pkg_info_action_conflicts_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_conflicts_entry, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_conflicts_entry), FALSE);

  pkg_info_action_suggests_label = gtk_label_new (_("Suggests"));
  gtk_widget_set_name (pkg_info_action_suggests_label, "pkg_info_action_suggests_label");
  gtk_widget_show (pkg_info_action_suggests_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_suggests_label, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_suggests_label), 0, 0.5);

  pkg_info_action_suggests_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_suggests_entry, "pkg_info_action_suggests_entry");
  gtk_widget_show (pkg_info_action_suggests_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_suggests_entry, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_suggests_entry), FALSE);

  pkg_info_action_mirror_label = gtk_label_new (_("Mirror"));
  gtk_widget_set_name (pkg_info_action_mirror_label, "pkg_info_action_mirror_label");
  gtk_widget_show (pkg_info_action_mirror_label);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_mirror_label, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pkg_info_action_mirror_label), 0, 0.5);

  pkg_info_action_mirror_entry = gtk_entry_new ();
  gtk_widget_set_name (pkg_info_action_mirror_entry, "pkg_info_action_mirror_entry");
  gtk_widget_show (pkg_info_action_mirror_entry);
  gtk_table_attach (GTK_TABLE (pkg_info_action_table), pkg_info_action_mirror_entry, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pkg_info_action_mirror_entry), FALSE);

  pkg_info_label = gtk_label_new (_("Package Information"));
  gtk_widget_set_name (pkg_info_label, "pkg_info_label");
  gtk_widget_show (pkg_info_label);
  gtk_frame_set_label_widget (GTK_FRAME (pkg_info_frame), pkg_info_label);

  label171 = gtk_label_new (_("<b>frame1</b>"));
  gtk_widget_set_name (label171, "label171");
  gtk_widget_show (label171);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label171);
  gtk_label_set_use_markup (GTK_LABEL (label171), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (trash, trash, "trash");
  GLADE_HOOKUP_OBJECT (trash, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (trash, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_frame, "pkg_info_frame");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_table, "pkg_info_action_table");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_name_label, "pkg_info_action_name_label");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_name_entry, "pkg_info_action_name_entry");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_description_label, "pkg_info_action_description_label");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_description_entry, "pkg_info_action_description_entry");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_version_label, "pkg_info_action_version_label");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_version_entry, "pkg_info_action_version_entry");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_size_label, "pkg_info_action_size_label");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_size_entry, "pkg_info_action_size_entry");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_isize_label, "pkg_info_action_isize_label");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_isize_entry, "pkg_info_action_isize_entry");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_required_label, "pkg_info_action_required_label");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_required_entry, "pkg_info_action_required_entry");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_conflicts_label, "pkg_info_action_conflicts_label");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_conflicts_entry, "pkg_info_action_conflicts_entry");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_suggests_label, "pkg_info_action_suggests_label");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_suggests_entry, "pkg_info_action_suggests_entry");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_mirror_label, "pkg_info_action_mirror_label");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_action_mirror_entry, "pkg_info_action_mirror_entry");
  GLADE_HOOKUP_OBJECT (trash, pkg_info_label, "pkg_info_label");
  GLADE_HOOKUP_OBJECT (trash, label171, "label171");

  return trash;
}

